/**
 * ROUTE-CONTRACT MATRIX — the 296 OpenAPI operations × persona expectations.
 * Data only (no .test suffix). Generated from audit/permission-audit/test-plan.md
 * §3 with the lead-approved corrections applied:
 *  - POST /api/servers/bulk/status → read-class, admin.read admitted;
 *  - GET /api/admin/events → T3 (SSE hijack, deny-side only);
 *  - GET /api/plugins/{name}/frontend-manifest → PU denied (admin.read gate,
 *    TARGET-VOCABULARY §2.1);
 *  - node/update/migration reads already admitted admin.read per decisions.
 *
 * Cell semantics: 'allow' = response MUST NOT be 403 (200/400/404/409 all prove
 * the gate opened); 'deny' = MUST be 403; 'scoped' = non-403, own-rows only;
 * 'masked' = deliberate masquerade denial — 403 OR 404 (server detail
 * routes hide existence from unauthorized callers; both prove no access).
 * 'skip' = persona not asserted (NA rows carry naReason).
 * The runner asserts AR/AW/PU/STAR; the KEY persona (§5b key-scope ceilings)
 * is deliberately NOT part of the generated runner — keyScope is data only.
 *
 * Drift guard: every api/openapi.json operation must have a row here —
 * a new route without a row fails the suite (route-contract.test.ts).
 */

export type ContractMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export type ContractCell = 'allow' | 'deny' | 'scoped' | 'masked' | 'skip';
export type ContractTier = 'T0' | 'T1' | 'T2' | 'T3' | 'NA';

export interface ContractRow {
  /** 'METHOD /path' exactly as in api/openapi.json. */
  op: string;
  method: ContractMethod;
  /** OpenAPI path template with {param} placeholders. */
  path: string;
  /** read | write | self | none — read-class admits admin.read. */
  klass: 'read' | 'write' | 'self' | 'none';
  ar: ContractCell;
  aw: ContractCell;
  pu: ContractCell;
  star: ContractCell;
  tier: ContractTier;
  /** T3 rows assert deny-side personas only (SSE / destructive / multipart). */
  denySideOnly?: boolean;
  /** Reason a row is N/A (agent/token/unauth/state-machine routes). */
  naReason?: string;
  /** Key-scope wiring state (§5b owns enforcement): Y wired · W to wire · — n/a. */
  keyScope: 'Y' | 'W' | '-';
  /** Body for write ops — default {} in the runner. Must pass route schemas
   * but die semantically AFTER the gate (nonexistent ids → 404/409/400). */
  payload?: Record<string, unknown>;
  /** Query string overrides. */
  query?: Record<string, string>;
  /** Explicit {param} → value substitutions (defaults: fixtures + nonexistent ids). */
  params?: Record<string, string>;
  /** Route not in openapi.json (SFTP/streams/inline) — excluded from the drift guard. */
  nonOpenapi?: boolean;
}

export const CONTRACT_ROWS: readonly ContractRow[] = [
  { op: 'GET /api/admin/api-keys', method: 'GET', path: '/api/admin/api-keys', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/api-keys', method: 'POST', path: '/api/admin/api-keys', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/api-keys/my-permissions', method: 'GET', path: '/api/admin/api-keys/my-permissions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/api-keys/permissions-catalog', method: 'GET', path: '/api/admin/api-keys/permissions-catalog', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/audit-logs', method: 'GET', path: '/api/admin/audit-logs', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/audit-logs/export', method: 'GET', path: '/api/admin/audit-logs/export', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/auth-lockouts', method: 'GET', path: '/api/admin/auth-lockouts', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/auth-lockouts/{lockoutId}', method: 'DELETE', path: '/api/admin/auth-lockouts/{lockoutId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/database-hosts', method: 'GET', path: '/api/admin/database-hosts', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/database-hosts', method: 'POST', path: '/api/admin/database-hosts', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/database-hosts/{hostId}', method: 'PUT', path: '/api/admin/database-hosts/{hostId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/database-hosts/{hostId}', method: 'DELETE', path: '/api/admin/database-hosts/{hostId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/database-hosts/{hostId}/ping', method: 'GET', path: '/api/admin/database-hosts/{hostId}/ping', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/db-status', method: 'GET', path: '/api/admin/db-status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/diagnostics/export', method: 'GET', path: '/api/admin/diagnostics/export', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/events', method: 'GET', path: '/api/admin/events', klass: 'read', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'SSE with custom session-token auth — not persona-injectable',},
  { op: 'GET /api/admin/health', method: 'GET', path: '/api/admin/health', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/ip-pools', method: 'GET', path: '/api/admin/ip-pools', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/ip-pools', method: 'POST', path: '/api/admin/ip-pools', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/ip-pools/{poolId}', method: 'PUT', path: '/api/admin/ip-pools/{poolId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/ip-pools/{poolId}', method: 'DELETE', path: '/api/admin/ip-pools/{poolId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/localization-settings', method: 'GET', path: '/api/admin/localization-settings', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/localization-settings', method: 'PUT', path: '/api/admin/localization-settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/mcp-settings', method: 'GET', path: '/api/admin/mcp-settings', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/mcp-settings', method: 'PUT', path: '/api/admin/mcp-settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/migration', method: 'GET', path: '/api/admin/migration', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/migration/catalyst-nodes', method: 'GET', path: '/api/admin/migration/catalyst-nodes', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/migration/start', method: 'POST', path: '/api/admin/migration/start', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'POST /api/admin/migration/test', method: 'POST', path: '/api/admin/migration/test', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'GET /api/admin/migration/{jobId}', method: 'GET', path: '/api/admin/migration/{jobId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/migration/{jobId}/cancel', method: 'POST', path: '/api/admin/migration/{jobId}/cancel', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'POST /api/admin/migration/{jobId}/pause', method: 'POST', path: '/api/admin/migration/{jobId}/pause', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'POST /api/admin/migration/{jobId}/resume', method: 'POST', path: '/api/admin/migration/{jobId}/resume', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'POST /api/admin/migration/{jobId}/retry/{stepId}', method: 'POST', path: '/api/admin/migration/{jobId}/retry/{stepId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'GET /api/admin/migration/{jobId}/steps', method: 'GET', path: '/api/admin/migration/{jobId}/steps', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/mod-manager', method: 'GET', path: '/api/admin/mod-manager', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/mod-manager', method: 'PUT', path: '/api/admin/mod-manager', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/nodes', method: 'GET', path: '/api/admin/nodes', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/oidc-config', method: 'GET', path: '/api/admin/oidc-config', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PATCH /api/admin/oidc-config', method: 'PATCH', path: '/api/admin/oidc-config', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/roles', method: 'GET', path: '/api/admin/roles', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/security-settings', method: 'GET', path: '/api/admin/security-settings', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/security-settings', method: 'PUT', path: '/api/admin/security-settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/servers', method: 'GET', path: '/api/admin/servers', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/servers/actions', method: 'POST', path: '/api/admin/servers/actions', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: 'Y',
    payload: {"serverIds": ["cnonexistent00000000contract"], "action": "start"},},
  // Lead ruling (2026-10): R-any by design — routes/admin.ts comment marks it
  // "available to all authenticated users". Operational constant (a byte
  // size) the file-manager UI reads before uploads; non-admin subusers with
  // file access need it; leaks no panel data. Same auth-only class as
  // provider-keys /status.
  { op: 'GET /api/admin/settings/file-tunnel-upload-limit', method: 'GET', path: '/api/admin/settings/file-tunnel-upload-limit', klass: 'read', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/smtp', method: 'GET', path: '/api/admin/smtp', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/smtp', method: 'PUT', path: '/api/admin/smtp', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/stats', method: 'GET', path: '/api/admin/stats', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/system-errors', method: 'GET', path: '/api/admin/system-errors', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/system-errors/export', method: 'GET', path: '/api/admin/system-errors/export', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/system-errors/resolve-all', method: 'POST', path: '/api/admin/system-errors/resolve-all', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/system-errors/{id}/resolve', method: 'POST', path: '/api/admin/system-errors/{id}/resolve', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/theme-settings', method: 'GET', path: '/api/admin/theme-settings', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PATCH /api/admin/theme-settings', method: 'PATCH', path: '/api/admin/theme-settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/update/check', method: 'POST', path: '/api/admin/update/check', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/update/settings', method: 'GET', path: '/api/admin/update/settings', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/update/settings', method: 'PUT', path: '/api/admin/update/settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/update/state', method: 'GET', path: '/api/admin/update/state', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/update/status', method: 'GET', path: '/api/admin/update/status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/update/trigger', method: 'POST', path: '/api/admin/update/trigger', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'GET /api/admin/users', method: 'GET', path: '/api/admin/users', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/users', method: 'POST', path: '/api/admin/users', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/users/{userId}', method: 'PUT', path: '/api/admin/users/{userId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/users/{userId}/accounts/{accountId}', method: 'DELETE', path: '/api/admin/users/{userId}/accounts/{accountId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/users/{userId}/ban', method: 'POST', path: '/api/admin/users/{userId}/ban', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/users/{userId}/delete', method: 'POST', path: '/api/admin/users/{userId}/delete', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/users/{userId}/enforce-2fa', method: 'PUT', path: '/api/admin/users/{userId}/enforce-2fa', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/users/{userId}/passkeys', method: 'DELETE', path: '/api/admin/users/{userId}/passkeys', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/admin/users/{userId}/servers', method: 'GET', path: '/api/admin/users/{userId}/servers', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/admin/users/{userId}/two-factor', method: 'DELETE', path: '/api/admin/users/{userId}/two-factor', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/admin/users/{userId}/unban', method: 'POST', path: '/api/admin/users/{userId}/unban', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PUT /api/admin/users/{userId}/verify-email', method: 'PUT', path: '/api/admin/users/{userId}/verify-email', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/alert-rules', method: 'GET', path: '/api/alert-rules', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/alert-rules', method: 'POST', path: '/api/alert-rules', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"name": "contract-probe", "type": "resource_threshold", "target": "server", "targetId": "__SERVER__", "conditions": {"cpuPercent": 90}, "actions": {"webhooks": []}},},
  { op: 'GET /api/alert-rules/{ruleId}', method: 'GET', path: '/api/alert-rules/{ruleId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/alert-rules/{ruleId}', method: 'PUT', path: '/api/alert-rules/{ruleId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"name": "contract-probe", "type": "resource_threshold", "target": "server", "targetId": "__SERVER__", "conditions": {"cpuPercent": 95}, "actions": {"webhooks": []}},},
  { op: 'DELETE /api/alert-rules/{ruleId}', method: 'DELETE', path: '/api/alert-rules/{ruleId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/alerts', method: 'GET', path: '/api/alerts', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/alerts/bulk-resolve', method: 'POST', path: '/api/alerts/bulk-resolve', klass: 'write', ar: 'scoped', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"alertIds": ["cnonexistent00000000contract"]},},
  { op: 'GET /api/alerts/stats', method: 'GET', path: '/api/alerts/stats', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/alerts/{alertId}', method: 'GET', path: '/api/alerts/{alertId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/alerts/{alertId}/deliveries', method: 'GET', path: '/api/alerts/{alertId}/deliveries', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/alerts/{alertId}/resolve', method: 'POST', path: '/api/alerts/{alertId}/resolve', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/auth/forgot-password', method: 'POST', path: '/api/auth/forgot-password', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'UNAUTH by design' },
  { op: 'POST /api/auth/login', method: 'POST', path: '/api/auth/login', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'UNAUTH by design' },
  { op: 'GET /api/auth/me', method: 'GET', path: '/api/auth/me', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/auth/profile', method: 'GET', path: '/api/auth/profile', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PATCH /api/auth/profile', method: 'PATCH', path: '/api/auth/profile', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/auth/profile/api-keys', method: 'GET', path: '/api/auth/profile/api-keys', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/auth/profile/audit-log', method: 'GET', path: '/api/auth/profile/audit-log', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/auth/profile/avatar', method: 'POST', path: '/api/auth/profile/avatar', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'DELETE /api/auth/profile/avatar', method: 'DELETE', path: '/api/auth/profile/avatar', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/auth/profile/delete', method: 'POST', path: '/api/auth/profile/delete', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/auth/profile/export', method: 'GET', path: '/api/auth/profile/export', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PATCH /api/auth/profile/preferences', method: 'PATCH', path: '/api/auth/profile/preferences', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/auth/profile/sso/unlink', method: 'POST', path: '/api/auth/profile/sso/unlink', klass: 'self', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/auth/register', method: 'POST', path: '/api/auth/register', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'UNAUTH by design' },
  { op: 'POST /api/auth/reset-password/validate', method: 'POST', path: '/api/auth/reset-password/validate', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'UNAUTH by design' },
  { op: 'GET /api/dashboard/activity', method: 'GET', path: '/api/dashboard/activity', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/dashboard/resources', method: 'GET', path: '/api/dashboard/resources', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/dashboard/stats', method: 'GET', path: '/api/dashboard/stats', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/internal/file-tunnel/poll', method: 'GET', path: '/api/internal/file-tunnel/poll', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'AGENT-INTERNAL by design' },
  { op: 'POST /api/internal/file-tunnel/response/{requestId}', method: 'POST', path: '/api/internal/file-tunnel/response/{requestId}', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'AGENT-INTERNAL' },
  { op: 'POST /api/internal/file-tunnel/response/{requestId}/stream', method: 'POST', path: '/api/internal/file-tunnel/response/{requestId}/stream', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'AGENT-INTERNAL' },
  { op: 'GET /api/internal/file-tunnel/upload/{requestId}', method: 'GET', path: '/api/internal/file-tunnel/upload/{requestId}', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'AGENT-INTERNAL' },
  { op: 'GET /api/locations', method: 'GET', path: '/api/locations', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/locations', method: 'POST', path: '/api/locations', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/locations/{locationId}', method: 'GET', path: '/api/locations/{locationId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/locations/{locationId}', method: 'PUT', path: '/api/locations/{locationId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/locations/{locationId}', method: 'DELETE', path: '/api/locations/{locationId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    params: {"locationId": "cnonexistent00000000contract"},},
  { op: 'GET /api/nests', method: 'GET', path: '/api/nests', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nests', method: 'POST', path: '/api/nests', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nests/{nestId}', method: 'GET', path: '/api/nests/{nestId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/nests/{nestId}', method: 'PUT', path: '/api/nests/{nestId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/nests/{nestId}', method: 'DELETE', path: '/api/nests/{nestId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    params: {"nestId": "cnonexistent00000000contract"},},
  { op: 'GET /api/nodes', method: 'GET', path: '/api/nodes', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/nodes', method: 'POST', path: '/api/nodes', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/nodes/accessible', method: 'GET', path: '/api/nodes/accessible', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'POST /api/nodes/assign-wildcard', method: 'POST', path: '/api/nodes/assign-wildcard', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'DELETE /api/nodes/assign-wildcard/{targetType}/{targetId}', method: 'DELETE', path: '/api/nodes/assign-wildcard/{targetType}/{targetId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'PATCH /api/nodes/auto-update', method: 'PATCH', path: '/api/nodes/auto-update', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}', method: 'GET', path: '/api/nodes/{nodeId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/nodes/{nodeId}', method: 'PUT', path: '/api/nodes/{nodeId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/nodes/{nodeId}', method: 'DELETE', path: '/api/nodes/{nodeId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    params: {"nodeId": "cnonexistent00000000contract"},},
  { op: 'GET /api/nodes/{nodeId}/agent/config', method: 'GET', path: '/api/nodes/{nodeId}/agent/config', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/nodes/{nodeId}/agent/config', method: 'PUT', path: '/api/nodes/{nodeId}/agent/config', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/agent/logs', method: 'GET', path: '/api/nodes/{nodeId}/agent/logs', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/agent/logs/stream', method: 'GET', path: '/api/nodes/{nodeId}/agent/logs/stream', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'POST /api/nodes/{nodeId}/agent/ping', method: 'POST', path: '/api/nodes/{nodeId}/agent/ping', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/agent/restart', method: 'POST', path: '/api/nodes/{nodeId}/agent/restart', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/agent/status', method: 'GET', path: '/api/nodes/{nodeId}/agent/status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/agent/update', method: 'POST', path: '/api/nodes/{nodeId}/agent/update', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/agent/update-status', method: 'GET', path: '/api/nodes/{nodeId}/agent/update-status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/allocations', method: 'GET', path: '/api/nodes/{nodeId}/allocations', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/allocations', method: 'POST', path: '/api/nodes/{nodeId}/allocations', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/allocations/bulk-delete', method: 'POST', path: '/api/nodes/{nodeId}/allocations/bulk-delete', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PATCH /api/nodes/{nodeId}/allocations/{allocationId}', method: 'PATCH', path: '/api/nodes/{nodeId}/allocations/{allocationId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/nodes/{nodeId}/allocations/{allocationId}', method: 'DELETE', path: '/api/nodes/{nodeId}/allocations/{allocationId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/api-key', method: 'GET', path: '/api/nodes/{nodeId}/api-key', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/api-key', method: 'POST', path: '/api/nodes/{nodeId}/api-key', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/assign', method: 'POST', path: '/api/nodes/{nodeId}/assign', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/assignments', method: 'GET', path: '/api/nodes/{nodeId}/assignments', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/nodes/{nodeId}/assignments/{assignmentId}', method: 'DELETE', path: '/api/nodes/{nodeId}/assignments/{assignmentId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/deployment-token', method: 'POST', path: '/api/nodes/{nodeId}/deployment-token', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/heartbeat', method: 'POST', path: '/api/nodes/{nodeId}/heartbeat', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'AGENT: agent-key auth, by design' },
  { op: 'POST /api/nodes/{nodeId}/host-network', method: 'POST', path: '/api/nodes/{nodeId}/host-network', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/nodes/{nodeId}/import-server', method: 'POST', path: '/api/nodes/{nodeId}/import-server', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/ip-availability', method: 'GET', path: '/api/nodes/{nodeId}/ip-availability', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/ip-pools', method: 'GET', path: '/api/nodes/{nodeId}/ip-pools', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/metrics', method: 'GET', path: '/api/nodes/{nodeId}/metrics', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/stats', method: 'GET', path: '/api/nodes/{nodeId}/stats', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/unregistered-containers', method: 'GET', path: '/api/nodes/{nodeId}/unregistered-containers', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/nodes/{nodeId}/unregistered-containers/{containerId}/suggest-template', method: 'GET', path: '/api/nodes/{nodeId}/unregistered-containers/{containerId}/suggest-template', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/plugins', method: 'GET', path: '/api/plugins', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'POST /api/plugins/install', method: 'POST', path: '/api/plugins/install', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'GET /api/plugins/marketplace', method: 'GET', path: '/api/plugins/marketplace', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'GET /api/plugins/marketplace/sources', method: 'GET', path: '/api/plugins/marketplace/sources', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'POST /api/plugins/marketplace/sources', method: 'POST', path: '/api/plugins/marketplace/sources', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'PATCH /api/plugins/marketplace/sources/{id}', method: 'PATCH', path: '/api/plugins/marketplace/sources/{id}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'DELETE /api/plugins/marketplace/sources/{id}', method: 'DELETE', path: '/api/plugins/marketplace/sources/{id}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'GET /api/plugins/{name}', method: 'GET', path: '/api/plugins/{name}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'PUT /api/plugins/{name}/config', method: 'PUT', path: '/api/plugins/{name}/config', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'POST /api/plugins/{name}/enable', method: 'POST', path: '/api/plugins/{name}/enable', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'GET /api/plugins/{name}/frontend-manifest', method: 'GET', path: '/api/plugins/{name}/frontend-manifest', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'PUT /api/plugins/{name}/permissions', method: 'PUT', path: '/api/plugins/{name}/permissions', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'POST /api/plugins/{name}/reload', method: 'POST', path: '/api/plugins/{name}/reload', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'POST /api/plugins/{name}/uninstall', method: 'POST', path: '/api/plugins/{name}/uninstall', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T2', keyScope: '-' },
  { op: 'GET /api/providers/status', method: 'GET', path: '/api/providers/status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'allow', star: 'allow', tier: 'T0', keyScope: '-' },
  { op: 'GET /api/roles', method: 'GET', path: '/api/roles', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/roles', method: 'POST', path: '/api/roles', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/roles/presets', method: 'GET', path: '/api/roles/presets', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/roles/permissions-catalog', method: 'GET', path: '/api/roles/permissions-catalog', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'GET /api/roles/users/{userId}/nodes', method: 'GET', path: '/api/roles/users/{userId}/nodes', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/roles/users/{userId}/roles', method: 'GET', path: '/api/roles/users/{userId}/roles', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/roles/{roleId}', method: 'GET', path: '/api/roles/{roleId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/roles/{roleId}', method: 'PUT', path: '/api/roles/{roleId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/roles/{roleId}', method: 'DELETE', path: '/api/roles/{roleId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/roles/{roleId}/nodes', method: 'GET', path: '/api/roles/{roleId}/nodes', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/roles/{roleId}/permissions', method: 'POST', path: '/api/roles/{roleId}/permissions', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/roles/{roleId}/permissions/*', method: 'DELETE', path: '/api/roles/{roleId}/permissions/*', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/roles/{roleId}/users/{userId}', method: 'POST', path: '/api/roles/{roleId}/users/{userId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/roles/{roleId}/users/{userId}', method: 'DELETE', path: '/api/roles/{roleId}/users/{userId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers', method: 'GET', path: '/api/servers', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers', method: 'POST', path: '/api/servers', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"name": "contract-gate-probe", "templateId": "cnonexistent00000000contract", "nodeId": "cnonexistent00000000contract", "locationId": "cnonexistent00000000contract", "primaryPort": 25599, "allocatedMemoryMb": 512, "allocatedCpuCores": 1, "allocatedDiskMb": 1024},},
  { op: 'DELETE /api/servers/bulk', method: 'DELETE', path: '/api/servers/bulk', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"serverIds": ["cnonexistent00000000contract"]},},
  { op: 'POST /api/servers/bulk/status', method: 'POST', path: '/api/servers/bulk/status', klass: 'read', ar: 'allow', aw: 'allow', pu: 'scoped', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"serverIds": ["__SERVER__"]},},
  { op: 'POST /api/servers/bulk/suspend', method: 'POST', path: '/api/servers/bulk/suspend', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"serverIds": ["cnonexistent00000000contract"]},},
  { op: 'POST /api/servers/bulk/unsuspend', method: 'POST', path: '/api/servers/bulk/unsuspend', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"serverIds": ["cnonexistent00000000contract"]},},
  { op: 'GET /api/servers/database-hosts', method: 'GET', path: '/api/servers/database-hosts', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/eula', method: 'POST', path: '/api/servers/eula', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"serverId": "__SERVER__", "accepted": true},},
  { op: 'POST /api/servers/invites/accept', method: 'POST', path: '/api/servers/invites/accept', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'TOKEN+auth (invite flow — §5b special)' },
  { op: 'POST /api/servers/invites/register', method: 'POST', path: '/api/servers/invites/register', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'TOKEN: by design' },
  { op: 'GET /api/servers/invites/{token}', method: 'GET', path: '/api/servers/invites/{token}', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'TOKEN: invite-token auth, by design' },
  { op: 'PATCH /api/servers/{id}/backup-settings', method: 'PATCH', path: '/api/servers/{id}/backup-settings', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'POST /api/servers/{id}/reset-crash-count', method: 'POST', path: '/api/servers/{id}/reset-crash-count', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PATCH /api/servers/{id}/restart-policy', method: 'PATCH', path: '/api/servers/{id}/restart-policy', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{id}/transfer', method: 'POST', path: '/api/servers/{id}/transfer', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"targetNodeId": "__NODE__"},},
  { op: 'GET /api/servers/{serverId}', method: 'GET', path: '/api/servers/{serverId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/servers/{serverId}', method: 'PUT', path: '/api/servers/{serverId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/servers/{serverId}', method: 'DELETE', path: '/api/servers/{serverId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/access', method: 'POST', path: '/api/servers/{serverId}/access', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"targetUserId": "cnonexistent00000000contract", "permissions": ["server.read"]},},
  { op: 'DELETE /api/servers/{serverId}/access/{targetUserId}', method: 'DELETE', path: '/api/servers/{serverId}/access/{targetUserId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/activity', method: 'GET', path: '/api/servers/{serverId}/activity', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/allocations', method: 'GET', path: '/api/servers/{serverId}/allocations', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/allocations', method: 'POST', path: '/api/servers/{serverId}/allocations', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"allocationId": "cnonexistent00000000contract"},},
  { op: 'POST /api/servers/{serverId}/allocations/primary', method: 'POST', path: '/api/servers/{serverId}/allocations/primary', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/servers/{serverId}/allocations/{containerPort}', method: 'DELETE', path: '/api/servers/{serverId}/allocations/{containerPort}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/archive', method: 'POST', path: '/api/servers/{serverId}/archive', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/backups', method: 'GET', path: '/api/servers/{serverId}/backups', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'POST /api/servers/{serverId}/backups', method: 'POST', path: '/api/servers/{serverId}/backups', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W',
    payload: {"name": "contract-probe"},},
  { op: 'GET /api/servers/{serverId}/backups/{backupId}', method: 'GET', path: '/api/servers/{serverId}/backups/{backupId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'DELETE /api/servers/{serverId}/backups/{backupId}', method: 'DELETE', path: '/api/servers/{serverId}/backups/{backupId}', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'GET /api/servers/{serverId}/backups/{backupId}/download', method: 'GET', path: '/api/servers/{serverId}/backups/{backupId}/download', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'POST /api/servers/{serverId}/backups/{backupId}/restore', method: 'POST', path: '/api/servers/{serverId}/backups/{backupId}/restore', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'POST /api/servers/{serverId}/cancel-install', method: 'POST', path: '/api/servers/{serverId}/cancel-install', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/clone', method: 'POST', path: '/api/servers/{serverId}/clone', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"name": "contract-clone-probe", "mode": "full", "targetNodeId": "__NODE__"},},
  { op: 'POST /api/servers/{serverId}/clone/preflight', method: 'POST', path: '/api/servers/{serverId}/clone/preflight', klass: 'read', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"mode": "full", "targetNodeId": "__NODE__"},},
  { op: 'POST /api/servers/{serverId}/clone/{cloneId}/retry', method: 'POST', path: '/api/servers/{serverId}/clone/{cloneId}/retry', klass: 'write', ar: 'masked', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/cs2/frameworks', method: 'GET', path: '/api/servers/{serverId}/cs2/frameworks', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/cs2/frameworks/{frameworkId}/install', method: 'POST', path: '/api/servers/{serverId}/cs2/frameworks/{frameworkId}/install', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/cs2/frameworks/{frameworkId}/releases', method: 'GET', path: '/api/servers/{serverId}/cs2/frameworks/{frameworkId}/releases', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/cs2/frameworks/{frameworkId}/uninstall', method: 'POST', path: '/api/servers/{serverId}/cs2/frameworks/{frameworkId}/uninstall', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/cs2/plugins', method: 'GET', path: '/api/servers/{serverId}/cs2/plugins', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/cs2/plugins/uninstall', method: 'POST', path: '/api/servers/{serverId}/cs2/plugins/uninstall', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"filename": "x.jar"},},
  { op: 'GET /api/servers/{serverId}/databases', method: 'GET', path: '/api/servers/{serverId}/databases', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'POST /api/servers/{serverId}/databases', method: 'POST', path: '/api/servers/{serverId}/databases', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"hostId": "cnonexistent00000000contract", "name": "contractprobe"},},
  { op: 'DELETE /api/servers/{serverId}/databases/{databaseId}', method: 'DELETE', path: '/api/servers/{serverId}/databases/{databaseId}', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'POST /api/servers/{serverId}/databases/{databaseId}/rotate', method: 'POST', path: '/api/servers/{serverId}/databases/{databaseId}/rotate', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'GET /api/servers/{serverId}/files', method: 'GET', path: '/api/servers/{serverId}/files', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'POST /api/servers/{serverId}/files/archive-contents', method: 'POST', path: '/api/servers/{serverId}/files/archive-contents', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"archivePath": "/a.zip"},
  },
  { op: 'POST /api/servers/{serverId}/files/compress', method: 'POST', path: '/api/servers/{serverId}/files/compress', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"paths": ["/a.txt"], "archiveName": "a.zip"},},
  { op: 'POST /api/servers/{serverId}/files/create', method: 'POST', path: '/api/servers/{serverId}/files/create', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"path": "/contract-dir", "isDirectory": true},},
  { op: 'POST /api/servers/{serverId}/files/decompress', method: 'POST', path: '/api/servers/{serverId}/files/decompress', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"archivePath": "/a.zip", "targetPath": "/out"},
  },
  { op: 'DELETE /api/servers/{serverId}/files/delete', method: 'DELETE', path: '/api/servers/{serverId}/files/delete', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: {"path": "/nonexistent.txt"},
  },
  { op: 'GET /api/servers/{serverId}/files/download', method: 'GET', path: '/api/servers/{serverId}/files/download', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: {"path": "/nonexistent.txt"},},
  { op: 'POST /api/servers/{serverId}/files/permissions', method: 'POST', path: '/api/servers/{serverId}/files/permissions', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"path": "/a.txt", "mode": "644"},},
  { op: 'POST /api/servers/{serverId}/files/rename', method: 'POST', path: '/api/servers/{serverId}/files/rename', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"from": "/a.txt", "to": "/b.txt"},},
  { op: 'POST /api/servers/{serverId}/files/upload', method: 'POST', path: '/api/servers/{serverId}/files/upload', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T3', keyScope: 'Y', denySideOnly: true },
  { op: 'POST /api/servers/{serverId}/files/write', method: 'POST', path: '/api/servers/{serverId}/files/write', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: {"path": "/contract.txt", "content": "x"},},
  { op: 'POST /api/servers/{serverId}/install', method: 'POST', path: '/api/servers/{serverId}/install', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/invites', method: 'GET', path: '/api/servers/{serverId}/invites', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/invites', method: 'POST', path: '/api/servers/{serverId}/invites', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"email": "contract-invitee@example.com", "permissions": ["server.read"]},},
  { op: 'DELETE /api/servers/{serverId}/invites/{inviteId}', method: 'DELETE', path: '/api/servers/{serverId}/invites/{inviteId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/invites/{inviteId}/regenerate', method: 'POST', path: '/api/servers/{serverId}/invites/{inviteId}/regenerate', klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/kill', method: 'POST', path: '/api/servers/{serverId}/kill', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'GET /api/servers/{serverId}/logs', method: 'GET', path: '/api/servers/{serverId}/logs', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/metrics', method: 'GET', path: '/api/servers/{serverId}/metrics', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/mod-manager/check-updates', method: 'POST', path: '/api/servers/{serverId}/mod-manager/check-updates', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/mod-manager/game-versions', method: 'GET', path: '/api/servers/{serverId}/mod-manager/game-versions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth"},},
  { op: 'POST /api/servers/{serverId}/mod-manager/install', method: 'POST', path: '/api/servers/{serverId}/mod-manager/install', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"provider": "modrinth", "projectId": "none", "versionId": "none", "target": "mods"},
  },
  { op: 'GET /api/servers/{serverId}/mod-manager/installed', method: 'GET', path: '/api/servers/{serverId}/mod-manager/installed', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/mod-manager/search', method: 'GET', path: '/api/servers/{serverId}/mod-manager/search', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth"},},
  { op: 'POST /api/servers/{serverId}/mod-manager/uninstall', method: 'POST', path: '/api/servers/{serverId}/mod-manager/uninstall', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"filename": "x.jar"},},
  { op: 'POST /api/servers/{serverId}/mod-manager/update', method: 'POST', path: '/api/servers/{serverId}/mod-manager/update', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"filenames": ["x.jar"]},},
  { op: 'GET /api/servers/{serverId}/mod-manager/versions', method: 'GET', path: '/api/servers/{serverId}/mod-manager/versions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth", "projectId": "none"},},
  { op: 'GET /api/servers/{serverId}/permissions', method: 'GET', path: '/api/servers/{serverId}/permissions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/plugin-manager/check-updates', method: 'POST', path: '/api/servers/{serverId}/plugin-manager/check-updates', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/plugin-manager/game-versions', method: 'GET', path: '/api/servers/{serverId}/plugin-manager/game-versions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth"},},
  { op: 'POST /api/servers/{serverId}/plugin-manager/install', method: 'POST', path: '/api/servers/{serverId}/plugin-manager/install', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"provider": "modrinth", "projectId": "none", "versionId": "none", "target": "plugins"},
  },
  { op: 'GET /api/servers/{serverId}/plugin-manager/installed', method: 'GET', path: '/api/servers/{serverId}/plugin-manager/installed', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/plugin-manager/search', method: 'GET', path: '/api/servers/{serverId}/plugin-manager/search', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth"},},
  { op: 'POST /api/servers/{serverId}/plugin-manager/uninstall', method: 'POST', path: '/api/servers/{serverId}/plugin-manager/uninstall', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"filename": "x.jar"},},
  { op: 'POST /api/servers/{serverId}/plugin-manager/update', method: 'POST', path: '/api/servers/{serverId}/plugin-manager/update', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"filenames": ["x.jar"]},},
  { op: 'GET /api/servers/{serverId}/plugin-manager/versions', method: 'GET', path: '/api/servers/{serverId}/plugin-manager/versions', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    query: {"provider": "modrinth", "projectId": "none"},},
  { op: 'POST /api/servers/{serverId}/rebuild', method: 'POST', path: '/api/servers/{serverId}/rebuild', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/reinstall', method: 'POST', path: '/api/servers/{serverId}/reinstall', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/restart', method: 'POST', path: '/api/servers/{serverId}/restart', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'POST /api/servers/{serverId}/restore', method: 'POST', path: '/api/servers/{serverId}/restore', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/start', method: 'POST', path: '/api/servers/{serverId}/start', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'GET /api/servers/{serverId}/stats', method: 'GET', path: '/api/servers/{serverId}/stats', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/stats/history', method: 'GET', path: '/api/servers/{serverId}/stats/history', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/stop', method: 'POST', path: '/api/servers/{serverId}/stop', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y' },
  { op: 'POST /api/servers/{serverId}/storage/resize', method: 'POST', path: '/api/servers/{serverId}/storage/resize', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"allocatedDiskMb": 2048},},
  { op: 'POST /api/servers/{serverId}/suspend', method: 'POST', path: '/api/servers/{serverId}/suspend', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/tasks', method: 'GET', path: '/api/servers/{serverId}/tasks', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/tasks', method: 'POST', path: '/api/servers/{serverId}/tasks', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"name": "contract-probe", "action": "restart", "schedule": "0 3 * * *"},},
  { op: 'GET /api/servers/{serverId}/tasks/{taskId}', method: 'GET', path: '/api/servers/{serverId}/tasks/{taskId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/servers/{serverId}/tasks/{taskId}', method: 'PUT', path: '/api/servers/{serverId}/tasks/{taskId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/servers/{serverId}/tasks/{taskId}', method: 'DELETE', path: '/api/servers/{serverId}/tasks/{taskId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/tasks/{taskId}/execute', method: 'POST', path: '/api/servers/{serverId}/tasks/{taskId}/execute', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/transfer-candidates', method: 'GET', path: '/api/servers/{serverId}/transfer-candidates', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/servers/{serverId}/transfer-ownership', method: 'POST', path: '/api/servers/{serverId}/transfer-ownership', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    payload: {"newOwnerId": "cnonexistent00000000contract"},},
  { op: 'POST /api/servers/{serverId}/unsuspend', method: 'POST', path: '/api/servers/{serverId}/unsuspend', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'GET /api/servers/{serverId}/variables', method: 'GET', path: '/api/servers/{serverId}/variables', klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'PATCH /api/servers/{serverId}/variables', method: 'PATCH', path: '/api/servers/{serverId}/variables', klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'W' },
  { op: 'GET /api/settings/locale', method: 'GET', path: '/api/settings/locale', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'PUBLIC: no auth, settings.ts:30-48' },
  { op: 'POST /api/setup/complete', method: 'POST', path: '/api/setup/complete', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'STATE-MACHINE' },
  { op: 'GET /api/setup/environment', method: 'GET', path: '/api/setup/environment', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'STATE-MACHINE: pre-init only' },
  { op: 'GET /api/setup/status', method: 'GET', path: '/api/setup/status', klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-', naReason: 'STATE-MACHINE' },
  { op: 'GET /api/templates', method: 'GET', path: '/api/templates', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/templates', method: 'POST', path: '/api/templates', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/templates/import-pterodactyl', method: 'POST', path: '/api/templates/import-pterodactyl', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'POST /api/templates/import-pterodactyl-batch', method: 'POST', path: '/api/templates/import-pterodactyl-batch', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T3', keyScope: '-', denySideOnly: true },
  { op: 'GET /api/templates/{templateId}', method: 'GET', path: '/api/templates/{templateId}', klass: 'read', ar: 'allow', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'PUT /api/templates/{templateId}', method: 'PUT', path: '/api/templates/{templateId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-' },
  { op: 'DELETE /api/templates/{templateId}', method: 'DELETE', path: '/api/templates/{templateId}', klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: '-',
    params: {"templateId": "cnonexistent00000000contract"},},
];

// ── Routes excluded from the HTTP persona harness — excluded from the drift
// guard, with N/A rows documenting why they cannot be exercised here. SSE
// routes are T3 (reply hijack — deny-side only) where their gates apply.
// (SFTP routes moved to routes/sftp.ts and now appear in the spec — their
// rows above carry no nonOpenapi flag.)
const NON_OPENAPI_ROWS: readonly ContractRow[] = [
  { op: 'DELETE /api/admin/api-keys/{id}', method: 'DELETE', path: '/api/admin/api-keys/{id}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'API-key detail lifecycle — harness has no API-key fixture/token context' },
  { op: 'GET /api/admin/api-keys/{id}', method: 'GET', path: '/api/admin/api-keys/{id}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'API-key detail lifecycle — harness has no API-key fixture/token context' },
  { op: 'GET /api/admin/api-keys/{id}/usage', method: 'GET', path: '/api/admin/api-keys/{id}/usage',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'API-key usage requires a real API-key identity and usage history' },
  { op: 'PATCH /api/admin/api-keys/{id}', method: 'PATCH', path: '/api/admin/api-keys/{id}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'API-key detail lifecycle — harness has no API-key fixture/token context' },
  { op: 'GET /api/agent/deploy-script', method: 'GET', path: '/api/agent/deploy-script',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'agent download response — requires deployment/runtime artifact context' },
  { op: 'GET /api/agent/download', method: 'GET', path: '/api/agent/download',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'binary agent download — not an HTTP persona contract probe' },
  { op: 'GET /api/agent/download-checksum', method: 'GET', path: '/api/agent/download-checksum',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'agent artifact checksum — requires deployment/runtime artifact context' },
  { op: 'GET /api/auth/oauth-providers', method: 'GET', path: '/api/auth/oauth-providers',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'OAuth provider discovery — external auth configuration, not persona-injectable' },
  { op: 'GET /api/auth/{path}', method: 'GET', path: '/api/auth/{path}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'Better Auth wildcard — auth state machine is outside the persona harness' },
  { op: 'POST /api/auth/{path}', method: 'POST', path: '/api/auth/{path}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'Better Auth wildcard — auth state machine is outside the persona harness' },
  { op: 'PATCH /api/auth/{path}', method: 'PATCH', path: '/api/auth/{path}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'Better Auth wildcard — auth state machine is outside the persona harness' },
  { op: 'PUT /api/auth/{path}', method: 'PUT', path: '/api/auth/{path}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'Better Auth wildcard — auth state machine is outside the persona harness' },
  { op: 'DELETE /api/auth/{path}', method: 'DELETE', path: '/api/auth/{path}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'Better Auth wildcard — auth state machine is outside the persona harness' },
  { op: 'GET /api/deploy/{token}', method: 'GET', path: '/api/deploy/{token}',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'deployment token flow — requires a real node deployment token' },
  { op: 'GET /api/health', method: 'GET', path: '/api/health',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'health probe — unauthenticated infrastructure endpoint' },
  { op: 'GET /api/theme-settings/public', method: 'GET', path: '/api/theme-settings/public',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'public bootstrap settings — unauthenticated endpoint' },
  { op: 'GET /api/update/check', method: 'GET', path: '/api/update/check',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'update check — external release/runtime state is not fixture-driven' },
  { op: 'GET /health', method: 'GET', path: '/health',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'health probe — unauthenticated infrastructure endpoint' },
  { op: 'POST /api/agent/sftp/validate-token', method: 'POST', path: '/api/agent/sftp/validate-token',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'agent SFTP token validation — requires agent credentials' },
  { op: 'POST /api/client-errors', method: 'POST', path: '/api/client-errors',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'client error ingestion — telemetry endpoint, not an access contract' },
  { op: 'POST /api/system-errors/report', method: 'POST', path: '/api/system-errors/report',
    klass: 'none', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'system error ingestion — telemetry endpoint, not an access contract' },
  { op: 'GET /api/sftp/connection-info', method: 'GET', path: '/api/sftp/connection-info',
    klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: { serverId: '__SERVER__' } },
  { op: 'POST /api/sftp/rotate-token', method: 'POST', path: '/api/sftp/rotate-token',
    // write action, but the sftp design (TARGET-VOCAB §5) lets read-capable
    // callers rotate — decideServerAccess(file.read) admits admin.read.
    klass: 'write', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    payload: { serverId: '__SERVER__' } },
  { op: 'GET /api/sftp/tokens', method: 'GET', path: '/api/sftp/tokens',
    klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: { serverId: '__SERVER__' } },
  { op: 'DELETE /api/sftp/tokens/{targetUserId}', method: 'DELETE', path: '/api/sftp/tokens/{targetUserId}',
    klass: 'write', ar: 'masked', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: {"serverId": "__SERVER__"},},
  { op: 'DELETE /api/sftp/tokens', method: 'DELETE', path: '/api/sftp/tokens',
    klass: 'write', ar: 'deny', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T1', keyScope: 'Y',
    query: {"serverId": "__SERVER__"},},
  { op: 'GET /api/servers/{serverId}/console/stream', method: 'GET', path: '/api/servers/{serverId}/console/stream',
    klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T3', keyScope: 'Y',
     denySideOnly: true },
  { op: 'POST /api/servers/{serverId}/console/command', method: 'POST', path: '/api/servers/{serverId}/console/command',
    klass: 'write', ar: 'deny', aw: 'allow', pu: 'deny', star: 'allow', tier: 'T1', keyScope: 'Y',
     payload: {"command": "say contract"},},
  { op: 'GET /api/servers/{serverId}/events', method: 'GET', path: '/api/servers/{serverId}/events',
    klass: 'read', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
     denySideOnly: true,
    naReason: 'SSE with custom token auth — not persona-injectable',},
  { op: 'GET /api/servers/{serverId}/metrics/stream', method: 'GET', path: '/api/servers/{serverId}/metrics/stream',
    klass: 'read', ar: 'allow', aw: 'allow', pu: 'masked', star: 'allow', tier: 'T3', keyScope: '-',
     denySideOnly: true },
  { op: 'GET /api/agent/version', method: 'GET', path: '/api/agent/version',
    klass: 'read', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
     naReason: 'defined inline in src/server.ts — module extraction prerequisite (test-plan §5i)',},
  { op: 'GET /api/permissions/server', method: 'GET', path: '/api/permissions/server',
    klass: 'read', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
     naReason: 'defined inline in src/server.ts — module extraction prerequisite (test-plan §5i)',},
  { op: 'POST /api/mcp', method: 'POST', path: '/api/mcp',
    klass: 'write', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'mcp: master-switch gated — 404s identically while disabled', nonOpenapi: true },
  { op: 'GET /api/mcp', method: 'GET', path: '/api/mcp',
    klass: 'read', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'mcp: master-switch gated — 404s identically while disabled', nonOpenapi: true },
  { op: 'DELETE /api/mcp', method: 'DELETE', path: '/api/mcp',
    klass: 'write', ar: 'skip', aw: 'skip', pu: 'skip', star: 'skip', tier: 'NA', keyScope: '-',
    naReason: 'mcp: master-switch gated — 404s identically while disabled', nonOpenapi: true },
];

export const ALL_CONTRACT_ROWS: readonly ContractRow[] = [...CONTRACT_ROWS, ...NON_OPENAPI_ROWS];
