/**
 * Regression test: no live node credentials may be tracked in git.
 *
 * catalyst-agent/config.toml is a dev-machine artifact generated by
 * `db:seed` containing a real node_id + agent API key. It was
 * accidentally committed in the past (keys are visible in git history),
 * so this test asserts the file stays untracked and that no tracked
 * file contains raw catalyst_ API key material.
 */
import { execSync } from "child_process";
import { describe, it, expect } from "vitest";

// Anchor all git queries to the repository root (not process.cwd()): the
// vitest config may be invoked from the repo root or from catalyst-backend,
// and `git ls-files` output differs between those two CWDs.
const REPO_ROOT = execSync("git rev-parse --show-toplevel", {
  encoding: "utf-8",
  cwd: import.meta.dirname,
})
  .trim()
  .replace(/\\/g, "/");
const GIT_OPTS = { encoding: "utf-8", cwd: REPO_ROOT } as const;

function gitLsFiles(): string {
  try {
    return execSync("git ls-files", { ...GIT_OPTS });
  } catch {
    // Not a git checkout (e.g. exported tarball) — nothing to assert.
    return "";
  }
}

describe("secret hygiene: tracked files", () => {
  it("does not track catalyst-agent/config.toml", () => {
    const files = gitLsFiles();
    if (!files) return; // skip outside a git checkout
    const tracked = files.split("\n");
    expect(tracked).not.toContain("catalyst-agent/config.toml");
  });

  it("does not track any file containing raw agent API key material", () => {
    const files = gitLsFiles();
    if (!files) return;
    const tracked = files.split("\n").filter(Boolean);
    // Scan the working-tree contents of every tracked text file for a
    // raw (unhashed) agent API key. Hashed keys in src are fine — they
    // never start with the "catalyst_" prefix.
    const offenders: string[] = [];
    for (const f of tracked) {
      if (f.startsWith("catalyst-agent/target/") || f.startsWith("node_modules/")) continue;
      try {
        const content = execSync(
          `git show "HEAD:${f.replace(/"/g, '\\"')}" 2>/dev/null`,
          { encoding: "utf-8", maxBuffer: 32 * 1024 * 1024, cwd: REPO_ROOT },
        );
        if (/catalyst_[A-Za-z0-9]{20,}/.test(content)) offenders.push(f);
      } catch {
        // binary or unreadable — skip
      }
    }
    expect(offenders).toEqual([]);
  });
});
