packages:
  - catalyst-backend
  - catalyst-frontend
  - catalyst-shared
  - catalyst-plugins/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  prisma: true
  ssh2: true
