-- AlterTable
ALTER TABLE "Node" ADD COLUMN IF NOT EXISTS "memoryOverallocatePercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Node" ADD COLUMN IF NOT EXISTS "cpuOverallocatePercent" INTEGER NOT NULL DEFAULT 0;
