import {
  File,
  FileJson,
  FileCode,
  FileText,
  FileImage,
  FileArchive,
  FileSpreadsheet,
  Folder,
  Settings,
  Terminal,
  Binary,
  Braces,
  ScrollText,
  Database,
  Code2,
  BookOpen,
  Hash,
  Coffee,
  Globe,
  FileKey,
} from 'lucide-react';

const EXT_MAP: Record<string, { icon: React.ElementType; color: string; label: string }> = {
  json: { icon: FileJson, color: 'text-amber-500', label: 'JSON' },
  js: { icon: FileCode, color: 'text-yellow-500', label: 'JavaScript' },
  jsx: { icon: FileCode, color: 'text-sky-400', label: 'JSX' },
  ts: { icon: FileCode, color: 'text-blue-500', label: 'TypeScript' },
  tsx: { icon: FileCode, color: 'text-sky-400', label: 'TSX' },
  py: { icon: Coffee, color: 'text-yellow-400', label: 'Python' },
  java: { icon: Coffee, color: 'text-orange-500', label: 'Java' },
  rs: { icon: Code2, color: 'text-orange-600', label: 'Rust' },
  go: { icon: Code2, color: 'text-cyan-400', label: 'Go' },
  c: { icon: Code2, color: 'text-slate-500', label: 'C' },
  cpp: { icon: Code2, color: 'text-indigo-400', label: 'C++' },
  h: { icon: Code2, color: 'text-slate-400', label: 'Header' },
  cs: { icon: Code2, color: 'text-violet-400', label: 'C#' },
  php: { icon: Globe, color: 'text-indigo-300', label: 'PHP' },
  rb: { icon: Code2, color: 'text-red-400', label: 'Ruby' },
  swift: { icon: Code2, color: 'text-orange-400', label: 'Swift' },
  kt: { icon: Code2, color: 'text-purple-400', label: 'Kotlin' },
  scala: { icon: Code2, color: 'text-red-300', label: 'Scala' },
  yaml: { icon: Braces, color: 'text-emerald-400', label: 'YAML' },
  yml: { icon: Braces, color: 'text-emerald-400', label: 'YAML' },
  xml: { icon: FileCode, color: 'text-orange-300', label: 'XML' },
  html: { icon: Globe, color: 'text-orange-400', label: 'HTML' },
  htm: { icon: Globe, color: 'text-orange-400', label: 'HTML' },
  css: { icon: FileText, color: 'text-sky-300', label: 'CSS' },
  scss: { icon: FileText, color: 'text-pink-300', label: 'SCSS' },
  sass: { icon: FileText, color: 'text-pink-300', label: 'Sass' },
  less: { icon: FileText, color: 'text-sky-300', label: 'Less' },
  sh: { icon: Terminal, color: 'text-lime-400', label: 'Shell' },
  bash: { icon: Terminal, color: 'text-lime-400', label: 'Bash' },
  zsh: { icon: Terminal, color: 'text-lime-400', label: 'Zsh' },
  ps1: { icon: Terminal, color: 'text-blue-300', label: 'PowerShell' },
  bat: { icon: Terminal, color: 'text-lime-400', label: 'Batch' },
  cmd: { icon: Terminal, color: 'text-lime-400', label: 'CMD' },
  md: { icon: BookOpen, color: 'text-slate-400', label: 'Markdown' },
  markdown: { icon: BookOpen, color: 'text-slate-400', label: 'Markdown' },
  txt: { icon: FileText, color: 'text-muted-foreground', label: 'Text' },
  log: { icon: ScrollText, color: 'text-muted-foreground', label: 'Log' },
  csv: { icon: FileSpreadsheet, color: 'text-green-500', label: 'CSV' },
  tsv: { icon: FileSpreadsheet, color: 'text-green-500', label: 'TSV' },
  sql: { icon: Database, color: 'text-sky-500', label: 'SQL' },
  db: { icon: Database, color: 'text-sky-500', label: 'Database' },
  sqlite: { icon: Database, color: 'text-sky-500', label: 'SQLite' },
  toml: { icon: Settings, color: 'text-slate-400', label: 'TOML' },
  ini: { icon: Settings, color: 'text-slate-400', label: 'INI' },
  cfg: { icon: Settings, color: 'text-slate-400', label: 'Config' },
  conf: { icon: Settings, color: 'text-slate-400', label: 'Config' },
  config: { icon: Settings, color: 'text-slate-400', label: 'Config' },
  properties: { icon: Settings, color: 'text-slate-400', label: 'Properties' },
  env: { icon: FileKey, color: 'text-emerald-400', label: 'Environment' },
  dockerfile: { icon: FileCode, color: 'text-blue-400', label: 'Dockerfile' },
  jar: { icon: Coffee, color: 'text-red-300', label: 'JAR' },
  war: { icon: Coffee, color: 'text-red-300', label: 'WAR' },
  class: { icon: Binary, color: 'text-red-300', label: 'Java Class' },
  pdf: { icon: FileText, color: 'text-red-500', label: 'PDF' },
  zip: { icon: FileArchive, color: 'text-amber-400', label: 'ZIP' },
  tar: { icon: FileArchive, color: 'text-amber-400', label: 'TAR' },
  gz: { icon: FileArchive, color: 'text-amber-400', label: 'Gzip' },
  tgz: { icon: FileArchive, color: 'text-amber-400', label: 'TGZ' },
  rar: { icon: FileArchive, color: 'text-amber-400', label: 'RAR' },
  '7z': { icon: FileArchive, color: 'text-amber-400', label: '7z' },
  bz2: { icon: FileArchive, color: 'text-amber-400', label: 'Bzip2' },
  xz: { icon: FileArchive, color: 'text-amber-400', label: 'XZ' },
  png: { icon: FileImage, color: 'text-purple-400', label: 'PNG' },
  jpg: { icon: FileImage, color: 'text-purple-400', label: 'JPEG' },
  jpeg: { icon: FileImage, color: 'text-purple-400', label: 'JPEG' },
  gif: { icon: FileImage, color: 'text-purple-400', label: 'GIF' },
  svg: { icon: FileImage, color: 'text-purple-400', label: 'SVG' },
  webp: { icon: FileImage, color: 'text-purple-400', label: 'WebP' },
  ico: { icon: FileImage, color: 'text-purple-400', label: 'Icon' },
  bmp: { icon: FileImage, color: 'text-purple-400', label: 'BMP' },
  tiff: { icon: FileImage, color: 'text-purple-400', label: 'TIFF' },
  mp3: { icon: File, color: 'text-pink-400', label: 'MP3' },
  wav: { icon: File, color: 'text-pink-400', label: 'WAV' },
  ogg: { icon: File, color: 'text-pink-400', label: 'OGG' },
  mp4: { icon: File, color: 'text-pink-400', label: 'MP4' },
  avi: { icon: File, color: 'text-pink-400', label: 'AVI' },
  mov: { icon: File, color: 'text-pink-400', label: 'MOV' },
  webm: { icon: File, color: 'text-pink-400', label: 'WebM' },
  mkv: { icon: File, color: 'text-pink-400', label: 'MKV' },
  exe: { icon: Binary, color: 'text-blue-400', label: 'Executable' },
  dll: { icon: Binary, color: 'text-blue-400', label: 'DLL' },
  so: { icon: Binary, color: 'text-blue-400', label: 'Shared Object' },
  dylib: { icon: Binary, color: 'text-blue-400', label: 'Dynamic Library' },
  wasm: { icon: Binary, color: 'text-violet-400', label: 'WASM' },
  lock: { icon: Hash, color: 'text-muted-foreground', label: 'Lockfile' },
};

export function getFileTypeInfo(name: string) {
  const ext = name.split('.').pop()?.toLowerCase() ?? '';
  return EXT_MAP[ext] ?? { icon: File, color: 'text-muted-foreground', label: 'File' };
}
