// Canned demo data for the static Cloudflare Pages deployment.
// Shapes mirror the real API responses so pages render without a backend.
// All ids/names are fictional and clearly marked as demo content.

const now = new Date().toISOString();

// Explicit grant list: the panel's server-permission checks match exact
// strings (no '*' wildcard at the server scope), so the demo admin needs
// every permission spelled out for all tabs to appear.
const allServerPermissions = [
  'server.read',
  'server.start',
  'server.stop',
  'server.install',
  'server.reinstall',
  'server.rebuild',
  'server.transfer',
  'server.delete',
  'server.schedule',
  'server.update',
  'console.read',
  'console.write',
  'file.read',
  'file.write',
  'backup.read',
  'backup.create',
  'backup.restore',
  'backup.delete',
  'database.read',
  'database.create',
  'database.rotate',
  'database.delete',
  'alert.read',
  'alert.create',
  'alert.update',
  'alert.delete',
];

export const demoUser = {
  id: 'demo-admin-1',
  email: 'demo@catalystctl.com',
  username: 'demo-admin',
  name: 'Demo Admin',
  firstName: 'Demo',
  lastName: 'Admin',
  image: undefined,
  role: 'admin',
  permissions: ['*'],
};

export const demoProfile = {
  id: demoUser.id,
  email: demoUser.email,
  username: demoUser.username,
  name: demoUser.name,
  firstName: 'Demo',
  lastName: 'Admin',
  image: null,
  emailVerified: true,
  twoFactorEnabled: false,
  hasPassword: false,
  createdAt: now,
  failedLoginAttempts: 0,
  lastFailedLogin: null,
  lastSuccessfulLogin: now,
  preferences: { theme: 'dark' },
  accounts: [],
};

export const demoServers = [
  {
    id: 'demo-server-1',
    ownerId: demoUser.id,
    owner: { id: demoUser.id, username: 'demo-admin', email: demoUser.email, name: 'Demo Admin' },
    name: 'demo-paper-01',
    status: 'running',
    nodeId: 'demo-node-1',
    templateId: 'demo-template-paper',
    nodeName: 'demo-eu-1',
    primaryPort: 25565,
    primaryIp: '203.0.113.10',
    portBindings: { 25565: 25565 },
    networkMode: 'bridge',
    environment: { EULA: 'TRUE', MEMORY: '4G' },
    startupCommand: 'java -Xmx4G -jar server.jar nogui',
    node: { name: 'demo-eu-1', hostname: 'demo-eu-1', publicAddress: '203.0.113.10', sftpPort: 2022, sftpEnabled: true },
    template: { name: 'PaperMC', image: 'ghcr.io/catalyst/paper:latest', startup: 'java -jar server.jar', features: { modManager: { providers: [{ id: 'modrinth', label: 'Modrinth' }], targets: ['mods'], paths: { mods: '/mods' } }, pluginManager: { providers: ['hangar'], paths: { plugins: '/plugins' } } } },
    cpuPercent: 23,
    memoryPercent: 54,
    memoryUsageMb: 2210,
    diskUsageMb: 6144,
    diskTotalMb: 20480,
    allocatedMemoryMb: 4096,
    allocatedCpuCores: 2,
    allocatedDiskMb: 20480,
    databaseAllocation: 1,
    restartPolicy: 'on-failure',
    crashCount: 0,
    maxCrashCount: 5,
    effectivePermissions: allServerPermissions,
  },
  {
    id: 'demo-server-2',
    ownerId: demoUser.id,
    owner: { id: demoUser.id, username: 'demo-admin', email: demoUser.email, name: 'Demo Admin' },
    name: 'demo-forge-01',
    status: 'stopped',
    nodeId: 'demo-node-1',
    templateId: 'demo-template-forge',
    nodeName: 'demo-eu-1',
    primaryPort: 25566,
    primaryIp: '203.0.113.10',
    portBindings: { 25565: 25566 },
    networkMode: 'bridge',
    environment: { EULA: 'TRUE', MEMORY: '6G' },
    startupCommand: 'java -Xmx6G -jar forge.jar nogui',
    node: { name: 'demo-eu-1', hostname: 'demo-eu-1', publicAddress: '203.0.113.10', sftpPort: 2022, sftpEnabled: true },
    template: { name: 'Forge', image: 'ghcr.io/catalyst/forge:latest', startup: 'java -jar forge.jar', features: { modManager: { providers: [{ id: 'curseforge', label: 'CurseForge' }], targets: ['mods'], paths: { mods: '/mods' } } } },
    cpuPercent: 0,
    memoryPercent: 0,
    memoryUsageMb: 0,
    diskUsageMb: 8192,
    diskTotalMb: 30720,
    allocatedMemoryMb: 6144,
    allocatedCpuCores: 4,
    allocatedDiskMb: 30720,
    databaseAllocation: 0,
    restartPolicy: 'on-failure',
    crashCount: 1,
    maxCrashCount: 5,
    effectivePermissions: allServerPermissions,
  },
  {
    id: 'demo-server-3',
    ownerId: demoUser.id,
    owner: { id: demoUser.id, username: 'demo-admin', email: demoUser.email, name: 'Demo Admin' },
    name: 'demo-vanilla-01',
    status: 'starting',
    operationStage: 'Pulling image',
    operationProgress: 62,
    nodeId: 'demo-node-2',
    templateId: 'demo-template-vanilla',
    nodeName: 'demo-na-1',
    primaryPort: 25567,
    primaryIp: '198.51.100.20',
    portBindings: { 25565: 25567 },
    networkMode: 'bridge',
    environment: { EULA: 'TRUE' },
    startupCommand: 'java -Xmx2G -jar server.jar nogui',
    node: { name: 'demo-na-1', hostname: 'demo-na-1', publicAddress: '198.51.100.20', sftpPort: 2022, sftpEnabled: false },
    template: { name: 'Vanilla', image: 'ghcr.io/catalyst/vanilla:latest', startup: 'java -jar server.jar' },
    cpuPercent: 8,
    memoryPercent: 12,
    memoryUsageMb: 256,
    diskUsageMb: 2048,
    diskTotalMb: 10240,
    allocatedMemoryMb: 2048,
    allocatedCpuCores: 1,
    allocatedDiskMb: 10240,
    databaseAllocation: 1,
    restartPolicy: 'always',
    crashCount: 0,
    maxCrashCount: 5,
    effectivePermissions: allServerPermissions,
  },
  {
    id: 'demo-server-4',
    ownerId: demoUser.id,
    owner: { id: demoUser.id, username: 'demo-admin', email: demoUser.email, name: 'Demo Admin' },
    name: 'demo-cs16-01',
    status: 'running',
    nodeId: 'demo-node-1',
    templateId: 'demo-template-cs16',
    nodeName: 'demo-eu-1',
    primaryPort: 27015,
    primaryIp: '203.0.113.10',
    portBindings: { 27015: 27015 },
    networkMode: 'bridge',
    environment: { HLDS_GAME: 'cstrike', MAXPLAYERS: '16', START_MAP: 'de_dust2' },
    startupCommand: './hlds_run -game cstrike +maxplayers 16 +map de_dust2',
    node: { name: 'demo-eu-1', hostname: 'demo-eu-1', publicAddress: '203.0.113.10', sftpPort: 2022, sftpEnabled: true },
    template: { name: 'Counter-Strike 1.6 (cstrike)', image: 'ghcr.io/catalyst/hlds-cstrike:latest', startup: './hlds_run -game cstrike' },
    cpuPercent: 11,
    memoryPercent: 9,
    memoryUsageMb: 190,
    diskUsageMb: 1024,
    diskTotalMb: 10240,
    allocatedMemoryMb: 2048,
    allocatedCpuCores: 1,
    allocatedDiskMb: 10240,
    databaseAllocation: 0,
    restartPolicy: 'always',
    crashCount: 0,
    maxCrashCount: 5,
    effectivePermissions: allServerPermissions,
  },
];

export const demoNodes = [
  {
    id: 'demo-node-1',
    name: 'demo-eu-1',
    locationId: 'demo-loc-eu',
    isOnline: true,
    agentVersion: '1.58.1',
    lastSeenAt: now,
    description: 'Demo node ( fictional data )',
    hostname: 'demo-eu-1',
    publicAddress: '203.0.113.10',
    sftpPort: 2022,
    sftpEnabled: true,
    maxMemoryMb: 32768,
    maxCpuCores: 16,
    memoryOverallocatePercent: 0,
    cpuOverallocatePercent: 0,
    createdAt: now,
    updatedAt: now,
    _count: { servers: 3 },
    location: { id: 'demo-loc-eu', name: 'Demo EU' },
    servers: [
      { id: 'demo-server-1', name: 'demo-paper-01', status: 'running' },
      { id: 'demo-server-2', name: 'demo-forge-01', status: 'stopped' },
      { id: 'demo-server-4', name: 'demo-cs16-01', status: 'running' },
    ],
  },
  {
    id: 'demo-node-2',
    name: 'demo-na-1',
    locationId: 'demo-loc-na',
    isOnline: false,
    agentVersion: '1.57.0',
    lastSeenAt: now,
    description: 'Demo offline node ( fictional data )',
    hostname: 'demo-na-1',
    publicAddress: '198.51.100.20',
    sftpPort: 2022,
    sftpEnabled: false,
    maxMemoryMb: 16384,
    maxCpuCores: 8,
    memoryOverallocatePercent: 0,
    cpuOverallocatePercent: 0,
    createdAt: now,
    updatedAt: now,
    _count: { servers: 1 },
    location: { id: 'demo-loc-na', name: 'Demo NA' },
    servers: [{ id: 'demo-server-3', name: 'demo-vanilla-01', status: 'starting' }],
  },
];

export const demoNodeStats = {
  nodeId: 'demo-node-1',
  isOnline: true,
  lastSeenAt: now,
  resources: {
    maxMemoryMb: 32768,
    maxCpuCores: 16,
    allocatedMemoryMb: 10240,
    allocatedCpuCores: 6,
    availableMemoryMb: 22528,
    availableCpuCores: 10,
    memoryUsagePercent: 31,
    cpuUsagePercent: 18,
    actualMemoryUsageMb: 8192,
    actualMemoryTotalMb: 32768,
    actualCpuPercent: 18,
    actualDiskUsageMb: 65536,
    actualDiskTotalMb: 262144,
  },
  servers: { total: 3, running: 2, stopped: 1 },
  lastMetricsUpdate: now,
  agentVersion: '1.58.1',
  agentUpdateAvailable: false,
  latestAgentVersion: '1.58.1',
};

export const demoDashboardStats = {
  servers: 4,
  serversOnline: 2,
  nodes: 2,
  nodesOnline: 1,
  alerts: 2,
  alertsUnacknowledged: 1,
};

export const demoDashboardActivity = [
  { id: 'demo-act-1', title: 'demo-paper-01 started', detail: 'Server is now running', time: '2 min ago', timestamp: now, type: 'server' },
  { id: 'demo-act-2', title: 'Backup completed', detail: 'demo-forge-01 nightly backup', time: '1 h ago', timestamp: now, type: 'backup' },
  { id: 'demo-act-3', title: 'demo-na-1 went offline', detail: 'Agent heartbeat missed', time: '3 h ago', timestamp: now, type: 'node' },
  { id: 'demo-act-4', title: 'High memory usage', detail: 'demo-paper-01 above 80%', time: '5 h ago', timestamp: now, type: 'alert' },
  { id: 'demo-act-5', title: 'Demo admin signed in', detail: 'Read-only demo session', time: '6 h ago', timestamp: now, type: 'user' },
];

export const demoResourceStats = {
  cpuUtilization: 18,
  memoryUtilization: 31,
  networkThroughput: 42,
};

export const demoTemplates = [
  {
    id: 'demo-template-paper',
    name: 'PaperMC (demo)',
    description: 'Demo template — fictional data, installs are disabled.',
    author: 'Catalyst Demo',
    version: '1.0.0',
    image: 'ghcr.io/catalyst/paper:latest',
    images: [{ name: 'latest', label: 'Latest', image: 'ghcr.io/catalyst/paper:latest' }],
    defaultImage: 'latest',
    startup: 'java -jar server.jar',
    stopCommand: 'stop',
    sendSignalTo: 'stdin',
    variables: [],
    supportedPorts: [25565],
    allocatedMemoryMb: 4096,
    allocatedCpuCores: 2,
  },
  {
    id: 'demo-template-forge',
    name: 'Forge (demo)',
    description: 'Demo template — fictional data, installs are disabled.',
    author: 'Catalyst Demo',
    version: '1.0.0',
    image: 'ghcr.io/catalyst/forge:latest',
    images: [{ name: 'latest', label: 'Latest', image: 'ghcr.io/catalyst/forge:latest' }],
    defaultImage: 'latest',
    startup: 'java -jar forge.jar',
    stopCommand: 'stop',
    sendSignalTo: 'stdin',
    variables: [],
    supportedPorts: [25565],
    allocatedMemoryMb: 6144,
    allocatedCpuCores: 4,
  },
  {
    id: 'demo-template-vanilla',
    name: 'Vanilla (demo)',
    description: 'Demo template — fictional data, installs are disabled.',
    author: 'Catalyst Demo',
    version: '1.0.0',
    image: 'ghcr.io/catalyst/vanilla:latest',
    images: [{ name: 'latest', label: 'Latest', image: 'ghcr.io/catalyst/vanilla:latest' }],
    defaultImage: 'latest',
    startup: 'java -jar server.jar',
    stopCommand: 'stop',
    sendSignalTo: 'stdin',
    variables: [],
    supportedPorts: [25565],
    allocatedMemoryMb: 2048,
    allocatedCpuCores: 1,
  },
  {
    id: 'demo-template-cs16',
    name: 'Counter-Strike 1.6 (cstrike) (demo)',
    description: 'Demo template — fictional data, installs are disabled.',
    author: 'Catalyst Demo',
    version: '1.0.0',
    image: 'ghcr.io/catalyst/hlds-cstrike:latest',
    images: [{ name: 'latest', label: 'Latest', image: 'ghcr.io/catalyst/hlds-cstrike:latest' }],
    defaultImage: 'latest',
    startup: './hlds_run -game cstrike',
    stopCommand: 'quit',
    sendSignalTo: 'stdin',
    variables: [],
    supportedPorts: [27015],
    allocatedMemoryMb: 2048,
    allocatedCpuCores: 1,
  },
];

export const demoAlerts = [
  {
    id: 'demo-alert-1',
    type: 'memory',
    severity: 'warning',
    title: 'High memory usage on demo-paper-01',
    message: 'Memory usage above 80% for 5 minutes (demo data).',
    serverId: 'demo-server-1',
    nodeId: 'demo-node-1',
    resolved: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-alert-2',
    type: 'node_offline',
    severity: 'critical',
    title: 'demo-na-1 went offline',
    message: 'Agent heartbeat missed (demo data).',
    serverId: null,
    nodeId: 'demo-node-2',
    resolved: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoDatabaseHosts = [
  { id: 'demo-db-host-1', name: 'demo-mysql-01', host: 'db.demo.invalid', port: 3306 },
];

export const demoDatabases = [
  {
    id: 'demo-db-1',
    name: 'demo_paper',
    username: 'demo_paper',
    password: 'demo-only-not-real',
    host: 'db.demo.invalid',
    port: 3306,
    hostId: 'demo-db-host-1',
    hostName: 'demo-mysql-01',
    createdAt: now,
  },
];

export const demoBackups = [
  {
    id: 'demo-backup-1',
    serverId: 'demo-server-1',
    name: 'nightly-demo-backup',
    path: '/backups/nightly-demo-backup.tar.gz',
    storageMode: 'local',
    sizeMb: 1240,
    checksum: 'demo',
    compressed: true,
    metadata: null,
    createdAt: now,
    restoredAt: null,
  },
];
export const demoLocations = [
  { id: 'demo-loc-eu', name: 'Demo EU', description: 'Fictional demo location' },
  { id: 'demo-loc-na', name: 'Demo NA', description: 'Fictional demo location' },
];

export const demoPublicTheme = {
  panelName: 'Catalyst (Demo)',
  logoUrl: null,
  faviconUrl: null,
  defaultTheme: 'dark',
  enabledThemes: ['dark', 'light'],
  primaryColor: '#c48d5a',
  secondaryColor: '#5ac4c2',
  accentColor: '#5a5cc4',
  authProviders: { whmcs: false, paymenter: false },
  // Palette generated from the catalystctl.com brand seed (#c48d5a) via
  // utils/generatePalette (split-complementary) — warm light surfaces.
  themeColors: {
    successColor: '#23b370',
    warningColor: '#df9516',
    dangerColor: '#d93f3f',
    infoColor: '#3f7ad9',
    darkBackground: '#161412',
    darkForeground: '#f3f2f2',
    darkCard: '#1c1a17',
    darkSurface1: '#25221e',
    darkSurface2: '#36322b',
    darkSurface3: '#4f4a40',
    darkBorder: '#3b3830',
    darkMuted: '#9d9a95',
    lightBackground: '#f6f5f4',
    lightForeground: '#171512',
    lightCard: '#fbfaf9',
    lightSurface1: '#fdfdfc',
    lightSurface2: '#efeeec',
    lightSurface3: '#e3e1de',
    lightBorder: '#e3e1de',
    lightMuted: '#827c73',
  },
  customCss: null,
};

export const demoAdminStats = { users: 4, servers: 4, nodes: 2, activeServers: 2 };

export const demoAdminUsers = [
  {
    id: demoUser.id,
    email: demoUser.email,
    username: demoUser.username,
    createdAt: now,
    updatedAt: now,
    roles: [{ id: 'demo-role-admin', name: 'Admin', permissions: ['*'] }],
    banned: false,
    emailVerified: true,
    twoFactorEnabled: false,
    lastSuccessfulLogin: now,
    _count: { passkeys: 0, sessions: 1 },
  },
  {
    id: 'demo-user-2',
    email: 'mod@catalystctl.com',
    username: 'demo-mod',
    createdAt: now,
    updatedAt: now,
    roles: [{ id: 'demo-role-mod', name: 'Moderator', permissions: ['server.read', 'server.start', 'server.stop'] }],
    banned: false,
    emailVerified: true,
    twoFactorEnabled: false,
    lastSuccessfulLogin: now,
    _count: { passkeys: 0, sessions: 0 },
  },
];

export const demoRoles = [
  { id: 'demo-role-admin', name: 'Admin', description: 'Full access (demo)', permissions: ['*'], userCount: 1, createdAt: now, updatedAt: now },
  { id: 'demo-role-mod', name: 'Moderator', description: 'Can start/stop servers (demo)', permissions: ['server.read', 'server.start', 'server.stop'], userCount: 1, createdAt: now, updatedAt: now },
  { id: 'demo-role-user', name: 'User', description: 'Own servers only (demo)', permissions: ['server.read'], userCount: 2, createdAt: now, updatedAt: now },
];

export const demoAuditLogs = [
  { id: 'demo-audit-1', action: 'server.start', resource: 'server', resourceId: 'demo-server-1', details: { name: 'demo-paper-01' }, timestamp: now, ipAddress: '203.0.113.5', userId: demoUser.id, user: { id: demoUser.id, username: 'demo-admin', email: demoUser.email } },
  { id: 'demo-audit-2', action: 'user.login', resource: 'auth', resourceId: demoUser.id, details: {}, timestamp: now, ipAddress: '203.0.113.5', userId: demoUser.id, user: { id: demoUser.id, username: 'demo-admin', email: demoUser.email } },
];

export const demoConsoleLines = [
  { stream: 'stdout', data: '[Server] Starting PaperMC (demo replay — live console is disabled in the demo)...', timestamp: now },
  { stream: 'stdout', data: '[Server] Loading world "demo-world"...', timestamp: now },
  { stream: 'stdout', data: '[Server] Done in 3.2s. Type "help" for commands.', timestamp: now },
];

export function demoMetricsHistory(points = 24) {
  const history = [];
  for (let i = points; i >= 0; i--) {
    history.push({
      cpuPercent: 15 + Math.round(10 * Math.sin(i / 3)),
      memoryUsageMb: 2000 + Math.round(300 * Math.sin(i / 4)),
      diskIoMb: 12,
      diskUsageMb: 6144,
      networkRxBytes: 1024 * (100 + i),
      networkTxBytes: 1024 * (80 + i),
      timestamp: new Date(Date.now() - i * 60_000).toISOString(),
    });
  }
  return history;
}

// Fictional Pterodactyl source panel for the migration demo flow.
export const demoMigrationTest = {
  success: true,
  version: '1.11.x (demo)',
  stats: { locations: 1, nodes: 1, nests: 2, users: 12, servers: 5 },
  nodesList: [
    {
      id: 1,
      name: 'ptero-node-01',
      fqdn: 'node01.ptero.demo.invalid',
      scheme: 'https',
      behindProxy: false,
      locationId: 1,
      locationName: 'Demo DC',
      memory: 32768,
      memoryOverallocate: 0,
      disk: 500000,
      diskOverallocate: 0,
      uploadSize: 100,
      maintenanceMode: false,
      serverCount: 2,
      allocations: [
        { id: 11, ip: '203.0.113.50', port: 25565, assigned: true, serverId: 101, primary: true },
        { id: 12, ip: '203.0.113.50', port: 25566, assigned: true, serverId: 102, primary: true },
        { id: 13, ip: '203.0.113.50', port: 25567, assigned: false, primary: false },
      ],
    },
  ],
  serversList: [
    {
      id: 101,
      uuid: 'demo-uuid-101',
      name: 'ptero-survival',
      nodeId: 1,
      nodeName: 'ptero-node-01',
      state: 'running',
      eggName: 'Paper',
      nestName: 'Minecraft',
      backupSlots: 3,
      currentBackups: 1,
      databases: 1,
      schedules: 2,
      subusers: 1,
      hasAllocation: true,
      memory: 4096,
      disk: 20480,
      cpu: 200,
      suspended: false,
    },
    {
      id: 102,
      uuid: 'demo-uuid-102',
      name: 'ptero-creative',
      nodeId: 1,
      nodeName: 'ptero-node-01',
      state: 'offline',
      eggName: 'Vanilla',
      nestName: 'Minecraft',
      backupSlots: 0,
      currentBackups: 0,
      databases: 0,
      schedules: 0,
      subusers: 0,
      hasAllocation: true,
      memory: 2048,
      disk: 10240,
      cpu: 100,
      suspended: false,
    },
  ],
};

export const demoMigrationJob = {
  id: 'demo-job-1',
  status: 'completed',
  sourceUrl: 'https://ptero.demo.invalid',
  sourceVersion: '1.11.x (demo)',
  config: { scope: 'full', nodeMappings: { '1': 'demo-node-1' }, serverMappings: {} },
  currentPhase: 'servers',
  progress: { phase: 'servers', total: 8, completed: 8, failed: 0, skipped: 0 },
  startedAt: now,
  completedAt: now,
  createdAt: now,
  updatedAt: now,
  _count: { steps: 8 },
};

export const demoMigrationSteps = [
  { id: 'demo-step-1', jobId: 'demo-job-1', phase: 'validate', action: 'validate_connection', status: 'completed', durationMs: 210 },
  { id: 'demo-step-2', jobId: 'demo-job-1', phase: 'locations', action: 'import_location', sourceId: '1', status: 'completed', durationMs: 120 },
  { id: 'demo-step-3', jobId: 'demo-job-1', phase: 'templates', action: 'import_template', sourceId: '5', status: 'completed', durationMs: 340 },
  { id: 'demo-step-4', jobId: 'demo-job-1', phase: 'users', action: 'import_user', sourceId: '7', status: 'completed', durationMs: 180 },
  { id: 'demo-step-5', jobId: 'demo-job-1', phase: 'nodes', action: 'import_node', sourceId: '1', targetId: 'demo-node-1', status: 'completed', durationMs: 410 },
  { id: 'demo-step-6', jobId: 'demo-job-1', phase: 'servers', action: 'import_server', sourceId: '101', status: 'completed', durationMs: 2200 },
  { id: 'demo-step-7', jobId: 'demo-job-1', phase: 'servers', action: 'import_server', sourceId: '102', status: 'completed', durationMs: 1800 },
  { id: 'demo-step-8', jobId: 'demo-job-1', phase: 'servers', action: 'verify_server', sourceId: '101', status: 'completed', durationMs: 260 },
];

// Example GDPR export payload for Profile → Export my data.
export function demoAccountExport() {
  return {
    exportedAt: new Date().toISOString(),
    demo: true,
    profile: demoProfile,
    preferences: { theme: 'dark', language: 'en' },
    servers: demoServers.map((s) => ({
      id: s.id,
      name: s.name,
      status: s.status,
      nodeId: s.nodeId,
      allocatedMemoryMb: s.allocatedMemoryMb,
      allocatedCpuCores: s.allocatedCpuCores,
      allocatedDiskMb: s.allocatedDiskMb,
    })),
    databases: demoDatabases,
    apiKeys: [],
    sessions: [
      {
        id: 'demo-session-1',
        ipAddress: '203.0.113.5',
        userAgent: 'DemoBrowser/1.0',
        createdAt: now,
        expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      },
    ],
    auditLog: demoAuditLogs,
  };
}
