// ═════════════════════════════════════════════════════════════════════════════
//  DEVELOPMENT ONLY — DO NOT RUN IN PRODUCTION
//  This seed script creates default data (admin user, templates, roles, node).
//  For new production installs use the /setup web route instead.
// ═════════════════════════════════════════════════════════════════════════════

import 'dotenv/config';
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import { auth, initAuth } from "../src/auth";
import { withRegistrationBypass } from "../src/lib/registration-gate.js";
initAuth();
import * as fs from 'fs';
import * as path from 'path';

// Prisma v7: Use adapter for PostgreSQL
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Function to convert HTTP URL to WebSocket URL
function toWebSocketUrl(url: string): string {
  if (url.startsWith('https://')) {
    return url.replace('https://', 'wss://');
  } else if (url.startsWith('http://')) {
    return url.replace('http://', 'ws://');
  }
  // If it's already a WebSocket URL, return as-is
  return url;
}

// Function to generate agent config.toml
function generateAgentConfig(node: any, backendUrl: string, apiKey: string): string {
  const wsUrl = toWebSocketUrl(backendUrl);
  const config = `# Catalyst Agent Configuration
# Auto-generated by seed script - DO NOT EDIT MANUALLY
# This file is regenerated when running db:seed

[server]
# Backend WebSocket URL (ws:// for development, wss:// for production)
backend_url = "${wsUrl}/ws"

# Unique node identifier (UUID from database)
node_id = "${node.id}"

# Agent API key (required for node authentication)
api_key = "${apiKey}"

# Hostname of this server
hostname = "${node.hostname}"

# Data directory for container volumes
data_dir = "/var/lib/catalyst"

# Directory for container console I/O (stdout/stderr FIFOs and log files).
# When not explicitly set, derives from data_dir (e.g. /var/lib/catalyst/console).
# Override this to place console logs on a separate filesystem.
# console_log_dir = "/var/log/catalyst/console"

# Maximum concurrent WebSocket connections
max_connections = 100

[sftp]
# Port the SFTP server listens on (default: 2022)
# port = 2022

# Path to the SSH host key file
# host_key_path = "/opt/catalyst-agent/sftp_host_key"

[containerd]
# Path to containerd socket
socket_path = "/run/containerd/containerd.sock"

# Containerd namespace for Catalyst containers
namespace = "catalyst"

# Directory where CNI network configuration files (.conflist) are stored
# cni_dir = "/etc/cni/net.d"

# Directory where CNI plugin binaries are installed
# cni_bin_dir = "/opt/cni/bin"

# Directory used by the host-local IPAM plugin for lease storage
# cni_data_dir = "/var/lib/cni/networks"

# Directory for CNI result/state files and port-forward state
# cni_results_dir = "/var/lib/cni/results"

# Bridge interface name for the default NAT network
# cni_bridge_name = "catalyst0"

# Subnet for the default bridge NAT network
# cni_bridge_subnet = "10.42.0.0/16"

# Systemd override directory for the containerd service unit
# systemd_override_dir = "/etc/systemd/system/containerd.service.d"

[networking]
# Configure one or more macvlan networks (optional). If omitted, the agent will
# provision a default mc-lan-static network based on the primary interface.
#
# [[networking.networks]]
# name = "mc-lan-static"
# interface = "eth0"
# cidr = "10.5.5.0/24"
# gateway = "10.5.5.1"
# range_start = "10.5.5.50"
# range_end = "10.5.5.200"
#
# [[networking.networks]]
# name = "mc-public"
# interface = "eth0"
# cidr = "98.168.52.0/24"
# gateway = "98.168.52.1"
# range_start = "98.168.52.50"
# range_end = "98.168.52.200"

[logging]
# Log level: trace, debug, info, warn, error
level = "info"

# Log format: json or text
format = "json"

[agent]
# Path to the agent's config.toml (used by NetworkManager for persistence).
# config_path = "/opt/catalyst-agent/config.toml"

# GitHub repository for agent release binaries.
# release_repo = "catalystctl/catalyst"
`;
  return config;
}

async function main() {
  // Prevent running in production
  if (process.env.NODE_ENV === 'production') {
    console.error('ERROR: Seed script must not be run in production.');
    console.error('For new production installs, open the /setup page in your browser.');
    console.error('If you really need to seed, set NODE_ENV=development or');
    console.error('SEED_ALLOW_DEFAULT_ADMIN=true to override this guard.');
    process.exit(1);
  }

  console.log('Seeding database...');
  console.log('⚠ WARNING: This creates a default admin user (admin@example.com / admin123).');
  console.log('  Change this password immediately after first login.\n');

  // Create location
  const location = await prisma.location.upsert({
    where: { name: "US East 1" },
    update: {},
    create: {
      name: "US East 1",
      description: "US East Coast Data Center",
    },
  });

  console.log("✓ Location created");

  // Create admin user via better-auth API
  // This ensures password is properly hashed and stored in the account table
  let user = await prisma.user.findUnique({
    where: { email: "admin@example.com" },
  });

  if (!user) {
    const signUpResponse = await withRegistrationBypass(() => auth.api.signUpEmail({
      headers: new Headers({
        origin: process.env.FRONTEND_URL || "http://localhost:5173",
      }),
      body: {
        email: "admin@example.com",
        password: "admin123",
        name: "admin",
        username: "admin",
      } as any,
      returnHeaders: true,
    }));

    const data =
      "headers" in signUpResponse && signUpResponse.response
        ? signUpResponse.response
        : (signUpResponse as any);
    user = data?.user;
  }

  if (!user) {
    throw new Error("Failed to create admin user via better-auth");
  }

  // Mark email as verified for development
  await prisma.user.update({
    where: { id: user.id },
    data: { emailVerified: true },
  });

  console.log("✓ Admin user created (admin@example.com / admin123)");

  // Create node
  const nodePublicAddress = process.env.SEED_NODE_PUBLIC_ADDRESS || "127.0.0.1";
  const nodeHostname = process.env.SEED_NODE_HOSTNAME || "localhost";
  const node = await prisma.node.upsert({
    where: { name: "development-1" },
    update: {},
    create: {
      name: "development-1",
      description: "Local development node",
      locationId: location.id,
      hostname: nodeHostname,
      publicAddress: nodePublicAddress,
      secret: "dev-secret-key-12345",
      maxMemoryMb: 32000,
      maxCpuCores: 16,
    },
  });

  console.log("✓ Node created");

  // Create API key for the agent
  let apiKey = "";
  try {
    const { createApiKey } = await import("../src/services/api-key-service");
    const apiKeyResponse = await createApiKey({
      name: `agent-${node.id.slice(0, 8)}`,
      userId: user.id,
      prefix: "catalyst",
      metadata: {
        nodeId: node.id,
        purpose: "agent",
      },
    });
    apiKey = apiKeyResponse.key;
    if (!apiKey) {
      console.warn("⚠ Failed to create agent API key");
    } else {
      console.log("✓ Agent API key created");
    }
  } catch (error) {
    console.error("✗ Failed to create agent API key:", error);
  }

  // Generate and write agent config.toml
  const backendUrl = process.env.BACKEND_EXTERNAL_ADDRESS || process.env.BACKEND_URL || "http://localhost:3000";
  const agentConfigPath = path.join(process.cwd(), "..", "catalyst-agent", "config.toml");
  const agentConfigContent = generateAgentConfig(node, backendUrl, apiKey);
  
  try {
    fs.writeFileSync(agentConfigPath, agentConfigContent, "utf-8");
    console.log("✓ Agent config.toml generated:", agentConfigPath);
  } catch (error) {
    console.error("✗ Failed to write agent config.toml:", error);
    console.error("  Expected path:", agentConfigPath);
    console.error("  The config file contains your API key — read it from the written file.");
  }

  // Create admin role
  const adminRole = await prisma.role.upsert({
    where: { name: "Administrator" },
    update: {
      description: "Full system access",
      permissions: ["*"],
    },
    create: {
      name: "Administrator",
      description: "Full system access",
      permissions: ["*"],
    },
  });

  console.log("✓ Administrator role created");

  // Create moderator role
  const moderatorRole = await prisma.role.upsert({
    where: { name: "Moderator" },
    update: {
      description: "Limited management permissions",
      permissions: [
        "node.read",
        "node.update",
        "node.view_stats",
        "location.read",
        "template.read",
        "user.read",
        "server.read",
        "server.start",
        "server.stop",
        "file.read",
        "file.write",
        "console.read",
        "console.write",
        "alert.read",
        "alert.create",
        "alert.update",
        "alert.delete",
      ],
    },
    create: {
      name: "Moderator",
      description: "Limited management permissions",
      permissions: [
        "node.read",
        "node.update",
        "node.view_stats",
        "location.read",
        "template.read",
        "user.read",
        "server.read",
        "server.start",
        "server.stop",
        "file.read",
        "file.write",
        "console.read",
        "console.write",
        "alert.read",
        "alert.create",
        "alert.update",
        "alert.delete",
      ],
    },
  });

  console.log("✓ Moderator role created");

  // Create user role
  const userRole = await prisma.role.upsert({
    where: { name: "User" },
    update: {
      description: "Basic user permissions",
      permissions: ["server.read"],
    },
    create: {
      name: "User",
      description: "Basic user permissions",
      permissions: ["server.read"],
    },
  });

  console.log("✓ User role created");

  // Assign admin role to user
  await prisma.user.update({
    where: { id: user.id },
    data: {
      role: "administrator",
      roles: {
        connect: { id: adminRole.id },
      },
    },
  });

  console.log("✓ Admin role assigned to default user");

  // Create Minecraft nest
  const minecraftNest = await prisma.nest.upsert({
    where: { name: "Minecraft" },
    update: {},
    create: {
      name: "Minecraft",
      description: "Minecraft server templates powered by mcjars.app",
      icon: "https://s3.mcjars.app/icons/vanilla.png",
      author: "Catalyst Maintainers",
    },
  });

  console.log("✓ Minecraft nest created");

  // Create universal Minecraft template using mcjars.app
  // Supports all server types: Vanilla, Paper, Fabric, Forge, NeoForge, Quilt,
  // Spigot, Purpur, Folia, Pufferfish, Mohist, Arclight, Sponge, Leaves, Canvas,
  // Velocity, BungeeCord, and more.
  const minecraftTemplate = await prisma.serverTemplate.upsert({
    where: { name: "Minecraft Server (Universal)" },
    update: {},
    create: {
      name: "Minecraft Server (Universal)",
      description:
        "Universal Minecraft server template supporting all major server types via mcjars.app. " +
        "Choose from Vanilla, Paper, Fabric, Forge, NeoForge, Quilt, Spigot, Purpur, Folia, " +
        "Pufferfish, Mohist, Arclight, Sponge, Leaves, Canvas, Velocity, BungeeCord, and more. " +
        "Server jars are automatically downloaded and installed from mcjars.app.",
      author: "Catalyst Maintainers",
      version: "1.0.0",
      image: "eclipse-temurin:21-jre",
      images: [
        { name: "temurin-25", label: "Eclipse Temurin 25 JRE (Java 25)", image: "eclipse-temurin:25-jre" },
        { name: "temurin-21", label: "Eclipse Temurin 21 JRE (Java 21)", image: "eclipse-temurin:21-jre" },
        { name: "temurin-17", label: "Eclipse Temurin 17 JRE (Java 17)", image: "eclipse-temurin:17-jre" },
        { name: "temurin-11", label: "Eclipse Temurin 11 JRE (Java 11)", image: "eclipse-temurin:11-jre" },
        { name: "temurin-8", label: "Eclipse Temurin 8 JRE (Java 8)", image: "eclipse-temurin:8-jre" },
      ],
      defaultImage: "eclipse-temurin:21-jre",
      installImage: "eclipse-temurin:21-jdk",
      installEntrypoint: "bash",
      startup:
        "java -Xms{{MEMORY}}M -Xmx{{MEMORY}}M -XX:+UseG1GC -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[ -f unix_args.txt ]] && printf %s '@unix_args.txt' || printf %s '-jar server.jar nogui' )",
      stopCommand: "stop",
      sendSignalTo: "SIGTERM",
      variables: [
        {
          name: "SERVER_TYPE",
          description: "Minecraft server software type",
          default: "paper",
          required: true,
          input: "select",
          rules: ["required", "in:vanilla,paper,purpur,spigot,folia,pufferfish,fabric,forge,neoforge,quilt,mohist,arclight,sponge,leaves,canvas,velocity,bungeecord"],
        },
        {
          name: "MINECRAFT_VERSION",
          description: "Minecraft version (e.g. 1.21.4) or 'latest' for the latest release",
          default: "latest",
          required: true,
          input: "text",
        },
        {
          name: "BUILD_NUMBER",
          description: "Specific build number or 'latest' for the latest build",
          default: "latest",
          required: false,
          input: "text",
        },
        {
          name: "MEMORY",
          description: "Amount of RAM in MB allocated to the JVM",
          default: "1024",
          required: true,
          input: "number",
        },
        {
          name: "EULA",
          description: "Agree to the Minecraft EULA (required for Java servers)",
          default: "false",
          required: true,
          input: "checkbox",
        },
        {
          name: "JVM_FLAGS",
          description: "Additional JVM flags to append to the startup command",
          default: "",
          required: false,
          input: "text",
        },
      ],
      installScript: `#!/bin/bash
# Unified Minecraft Server Installer via mcjars.app
# Supports: Vanilla, Paper, Fabric, Forge, NeoForge, Quilt, Spigot, Purpur,
# Folia, Pufferfish, Mohist, Arclight, Sponge, Leaves, Canvas, Velocity, BungeeCord

MCJARS_API="https://mcjars.app"
TYPE="\${SERVER_TYPE}"
VERSION="\${MINECRAFT_VERSION}"
BUILD_NUM="\${BUILD_NUMBER}"

echo "[mcjars] Starting installation for type=\${TYPE} version=\${VERSION} build=\${BUILD_NUM}"

# Resolve 'latest' version to an actual version string
if [ "\${VERSION}" = "latest" ] || [ -z "\${VERSION}" ]; then
  echo "[mcjars] Resolving latest supported release for \${TYPE}..."
  VERSION=$(curl -s "\${MCJARS_API}/api/v3/builds/types/\${TYPE}/versions" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    for v in data['versions']['data']:
        if v.get('supported') and v.get('type') == 'RELEASE':
            print(v['id'])
            sys.exit(0)
    for v in data['versions']['data']:
        if v.get('supported'):
            print(v['id'])
            sys.exit(0)
    print('ERROR: No supported versions found', file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    sys.exit(1)
" 2>&1)
  if echo "\${VERSION}" | grep -q '^ERROR'; then
    echo "[mcjars] Failed to resolve version: \${VERSION}"
    exit 1
  fi
  echo "[mcjars] Resolved latest version: \${VERSION}"
fi

# Get the required Java version from the mcjars API
JAVA_VER=$(curl -s "\${MCJARS_API}/api/v1/version/\${VERSION}" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get('version', {}).get('java', 21))
except Exception:
    print(21)
" 2>/dev/null || echo 21)
echo "[mcjars] Minecraft \${VERSION} requires Java \${JAVA_VER}"
echo "[mcjars] Ensure you selected the correct Java image variant"

# Resolve build UUID - latest or specific build number
if [ "\${BUILD_NUM}" = "latest" ] || [ -z "\${BUILD_NUM}" ]; then
  echo "[mcjars] Fetching latest build for \${TYPE} \${VERSION}..."
  BUILD_UUID=$(curl -s "\${MCJARS_API}/api/v3/builds/types/\${TYPE}/versions/\${VERSION}/latest" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    print(data['build']['uuid'])
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    sys.exit(1)
" 2>&1)
else
  echo "[mcjars] Fetching build \${BUILD_NUM} for \${TYPE} \${VERSION}..."
  BUILD_UUID=$(curl -s "\${MCJARS_API}/api/v1/builds/\${TYPE}/\${VERSION}" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    target = '\${BUILD_NUM}'
    for b in data['builds']:
        if str(b.get('buildNumber', '')) == target or b.get('name', '').lstrip('#') == target:
            print(b['uuid'])
            sys.exit(0)
    if data['builds']:
        print(data['builds'][0]['uuid'])
    else:
        print('ERROR: No builds found', file=sys.stderr)
        sys.exit(1)
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    sys.exit(1)
" 2>&1)
fi

if echo "\${BUILD_UUID}" | grep -q '^ERROR'; then
  echo "[mcjars] Failed to resolve build: \${BUILD_UUID}"
  exit 1
fi
echo "[mcjars] Build UUID: \${BUILD_UUID}"

# Fetch and execute the mcjars-generated install script
echo "[mcjars] Downloading install script from mcjars.app..."
curl -sL "\${MCJARS_API}/api/v1/script/\${BUILD_UUID}/bash" -o /tmp/mcjars_install.sh
if [ ! -s /tmp/mcjars_install.sh ]; then
  echo "[mcjars] ERROR: Failed to download install script"
  exit 1
fi

echo "[mcjars] Running mcjars install script..."
bash /tmp/mcjars_install.sh
rm -f /tmp/mcjars_install.sh

# Accept EULA if set
if [ "\${EULA}" = "true" ]; then
  echo "[mcjars] Accepting Minecraft EULA"
  echo "eula=true" > eula.txt
fi

# Verify installation
if [ -f server.jar ]; then
  SIZE=$(stat -c%s server.jar 2>/dev/null || stat -f%z server.jar 2>/dev/null || echo '?')
  echo "[mcjars] server.jar installed (\${SIZE} bytes)"
elif [ -f unix_args.txt ]; then
  echo "[mcjars] Forge/NeoForge installation detected (unix_args.txt present)"
else
  echo "[mcjars] WARNING: No server.jar or unix_args.txt found after installation"
fi

echo "[mcjars] Installation complete"
      `.trim(),
      supportedPorts: [25565, 25577],
      allocatedMemoryMb: 1024,
      allocatedCpuCores: 2,
      features: {
        restartOnExit: true,
        startupDetection: {
          done: ")! For help, type \"help\"",
        },
        iconUrl: "https://s3.mcjars.app/icons/vanilla.png",
        tags: ["minecraft", "mcjars", "java", "gaming"],
        updateUrl: "https://mcjars.app",
        modManager: {
          providers: ["curseforge", "modrinth"],
          targets: ["forge", "fabric", "neoforge", "quilt"],
        },
        pluginManager: {
          providers: ["modrinth", "spigot", "paper"],
        },
      },
      nestId: minecraftNest.id,
    },
  });

  console.log("✓ Minecraft Server (Universal) template created");

  // Create generic Node.js template
  await prisma.serverTemplate.upsert({
    where: { name: "Node.js Bot (Git Repository)" },
    update: {},
    create: {
      name: "Node.js Bot (Git Repository)",
      description:
        "Generic Node.js template that clones a Git repository, installs dependencies, and starts via .env command overrides.",
      author: "Catalyst Maintainers",
      version: "1.0.0",
      image: "node:20-bookworm-slim",
      images: [
        { name: "node-22", label: "Node.js 22", image: "node:22-bookworm-slim" },
        { name: "node-20", label: "Node.js 20 (LTS)", image: "node:20-bookworm-slim" },
        { name: "node-18", label: "Node.js 18", image: "node:18-bookworm-slim" },
      ],
      defaultImage: "node:20-bookworm-slim",
      installImage: "node:20-bookworm-slim",
      startup:
        "sh -lc 'set -a; [ -f .env ] && . ./.env; set +a; CMD=\"\${BOT_START_COMMAND:-\${START_COMMAND:-npm start}}\"; echo \"[Catalyst] Startup command: $CMD\"; exec sh -lc \"$CMD\"'",
      stopCommand: "exit",
      sendSignalTo: "SIGTERM",
      variables: [
        {
          name: "GIT_REPO",
          description: "Git clone URL for your bot repository",
          default: "",
          required: true,
          input: "text",
        },
        {
          name: "GIT_BRANCH",
          description: "Git branch or tag to deploy",
          default: "main",
          required: false,
          input: "text",
        },
        {
          name: "NPM_INSTALL_COMMAND",
          description: "Dependency install command run after clone",
          default: "npm install --no-audit --no-fund",
          required: false,
          input: "text",
        },
        {
          name: "START_COMMAND",
          description: "Fallback startup command when BOT_START_COMMAND is not set",
          default: "npm start",
          required: false,
          input: "text",
        },
        {
          name: "BOT_START_COMMAND",
          description: "Optional startup command override (also supports .env value)",
          default: "",
          required: false,
          input: "text",
        },
        {
          name: "PORT",
          description: "Application listen port (kept in sync with server primary port on start)",
          default: "3000",
          required: true,
          input: "number",
          rules: ["between:1024,65535"],
        },
        {
          name: "NODE_ENV",
          description: "Node.js runtime environment",
          default: "production",
          required: false,
          input: "text",
        },
      ],
      installScript: `#!/bin/sh
set -e

echo '[Catalyst] Starting Node.js bot installation...'

if ! command -v git >/dev/null 2>&1; then
  echo '[Catalyst] ERROR: git is required but not installed on this node.'
  exit 1
fi

# Prefer host npm; fallback to a containerized install if npm is unavailable.
run_dependency_install() {
  if command -v npm >/dev/null 2>&1; then
    sh -lc "$INSTALL_CMD"
    return
  fi

  echo '[Catalyst] npm not found on host; using containerized dependency install.'

  NODE_IMAGE="{{TEMPLATE_IMAGE}}"
  if [ -z "$NODE_IMAGE" ] || [ "$NODE_IMAGE" = "{{TEMPLATE_IMAGE}}" ]; then
    NODE_IMAGE="node:20-bookworm-slim"
  fi

  if command -v ctr >/dev/null 2>&1; then
    ctr run --rm --mount type=bind,src="{{SERVER_DIR}}",dst=/data,options=rbind:rw "$NODE_IMAGE" catalyst-npm-install sh -lc "cd /data && $INSTALL_CMD"
    return
  fi

  if command -v docker >/dev/null 2>&1; then
    docker run --rm -v "{{SERVER_DIR}}:/data" -w /data "$NODE_IMAGE" sh -lc "$INSTALL_CMD"
    return
  fi

  if command -v podman >/dev/null 2>&1; then
    podman run --rm -v "{{SERVER_DIR}}:/data" -w /data "$NODE_IMAGE" sh -lc "$INSTALL_CMD"
    return
  fi

  echo '[Catalyst] ERROR: npm not found and no container runtime (ctr/docker/podman) is available.'
  exit 1
}

REPO_URL="{{GIT_REPO}}"
BRANCH="{{GIT_BRANCH}}"
INSTALL_CMD="{{NPM_INSTALL_COMMAND}}"

if [ -z "$REPO_URL" ]; then
  echo '[Catalyst] ERROR: GIT_REPO is required.'
  exit 1
fi

if [ -z "$BRANCH" ]; then
  BRANCH="main"
fi

if [ -z "$INSTALL_CMD" ]; then
  INSTALL_CMD="npm install --no-audit --no-fund"
fi

mkdir -p {{SERVER_DIR}}
cd {{SERVER_DIR}}

if [ -d .git ]; then
  echo '[Catalyst] Existing repository detected, resetting to requested branch.'
  git remote set-url origin "$REPO_URL"
  git fetch --depth 1 origin "$BRANCH"
  git checkout -B "$BRANCH" "origin/$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  if [ "$(ls -A . 2>/dev/null)" ]; then
    echo '[Catalyst] Existing files found. Cleaning server directory before clone.'
    find . -mindepth 1 -maxdepth 1 -exec rm -rf {} +
  fi
  echo "[Catalyst] Cloning $REPO_URL (branch: $BRANCH)..."
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" .
fi

if [ ! -f package.json ]; then
  echo '[Catalyst] ERROR: package.json not found after clone.'
  exit 1
fi

echo "[Catalyst] Running dependency install: $INSTALL_CMD"
run_dependency_install

if [ ! -f .env ]; then
  cat > .env << 'ENVEOF'
# Optional runtime overrides
# BOT_START_COMMAND=npm start
# START_COMMAND=npm start
# PORT=3000
# NODE_ENV=production
ENVEOF
  echo '[Catalyst] Created default .env file (edit as needed).'
fi

echo '[Catalyst] Node.js bot installation complete.'
`,
      supportedPorts: [3000],
      allocatedMemoryMb: 1024,
      allocatedCpuCores: 1,
      features: {
        restartOnExit: true,
      },
    },
  });

  console.log("✓ Node.js template created");

  console.log("\nSeeding complete!");
  console.log("Default user: admin@example.com / admin123");
  console.log("Development node ready at:", node.publicAddress);
  console.log("Agent config.toml generated with all required variables:");
  console.log("  - node_id:", node.id);
  console.log("  - api_key:", apiKey ? "<generated>" : "(not created)");
  console.log("  - hostname:", node.hostname);
  console.log("  - backend_url:", toWebSocketUrl(backendUrl) + "/ws");
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
