/**
 * Authentication, registration, session, profile, setup-wizard and API-key
 * error codes. Values are part of the public API — the frontend translates them.
 */
export const AuthErrorCodes = {
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  AUTH_ACCOUNT_OWNS_SERVERS: "AUTH_ACCOUNT_OWNS_SERVERS",
  AUTH_EXPIRED: "AUTH_EXPIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_RESET_TOKEN: "AUTH_INVALID_RESET_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_INVALID_USERNAME: "AUTH_INVALID_USERNAME",
  AUTH_ONLY_SIGN_IN_METHOD: "AUTH_ONLY_SIGN_IN_METHOD",
  AUTH_REGISTRATION_FAILED: "AUTH_REGISTRATION_FAILED",
  AUTH_USERNAME_TAKEN: "AUTH_USERNAME_TAKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  SETUP_ALREADY_COMPLETED: "SETUP_ALREADY_COMPLETED",
  SETUP_OPERATOR_VERIFICATION_FAILED: "SETUP_OPERATOR_VERIFICATION_FAILED",
} as const;
