/**
 * DEPRECATED: Backend SFTP Server Stub
 *
 * The SFTP server has been moved to the node agent (catalyst-agent/src/sftp_server.rs).
 * The backend no longer runs its own SFTP server.
 *
 * Token generation and validation remain in the backend via
 * catalyst-backend/src/services/sftp-token-manager.ts.
 * The agent validates tokens via POST /api/agent/sftp/validate-token.
 *
 * This stub is kept for backward compatibility in case anything
 * still tries to import from this module.
 */

import type { Logger } from "pino";

/**
 * @deprecated SFTP server now runs on the node agent. This function is a no-op.
 */
export function startSFTPServer(logger: Logger) {
	logger.warn(
		"[DEPRECATED] startSFTPServer() called on backend — SFTP server has been moved to the node agent. " +
		"Use the agent's SFTP server (port 2022 by default) instead. " +
		"Tokens are still generated by the backend via /api/sftp/connection-info.",
	);
}
